### ISSUE TITLE
training never starts

### ISSUE THREAD

**Issue by WeissShahaf** [DeepLabCut/DeepLabCut#1443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

when trying to train a network, almost any network (dlcrnet cannot even be created).
everything runs until the "starting training..." message, but nothing ever happnes, even a week after the command.

### Operating System

operating system - win10

### DeepLabCut version

deeplabcut.__version__
'2.2rc3'

 tensorflow.__version__
'2.5.0'

### DeepLabCut mode

single animal

### Device type

GPU: RTX 3090
CPU: Intel(R) Xeon(R) Gold 5122 CPU @ 3.60GHz   3.59 GHz  (2 processors)

### Steps To Reproduce

in DEEPLABCUT (installed using pip) or in DLC2107 (installed using the conda environment from github)
2. either run deeplabcut from gui or by command line:
```python
In [1]: import deeplabcut
2021-07-28 14:32:26.795739: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudart64_110.dll

In [2]: import os
   ...: import tensorflow

In [3]: config_path = 'E:\DLC\GL999-sw-2021-07-26\config.yaml'^
   ...: deeplabcut.train_network(config_path, shuffle=1, trainingsetindex=0, gputouse=0, max_snapshots_to_keep=5, autotune=False, displayiters=100, saveiters=15000, maxiters=30000, allow_growth=True)
Selecting single-animal trainer
Config:
{'all_joints': [[0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [10]],
 'all_joints_names': ['Red',
                      'LeftHead',
                      'LeftHand',
                      'LeftLeg',
                      'Nose',
                      'Back',
                      'Pelvis',
                      'Green',
                      'RightHead',
                      'RightHand',
                      'RightLeg'],
 'alpha_r': 0.02,
 'batch_size': 1,
 'clahe': True,
 'claheratio': 0.1,
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_GL999Jul26\\GL999_sw95shuffle1.mat',
 'dataset_type': 'imgaug',
 'decay_steps': 30000,
 'deterministic': False,
 'display_iters': 1000,
 'edge': False,
 'emboss': {'alpha': [0.0, 1.0], 'embossratio': 0.1, 'strength': [0.5, 1.5]},
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'histeq': True,
 'histeqratio': 0.1,
 'init_weights': 'H:\\anaconda3\\envs\\DLC2107\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\mobilenet_v2_1.0_224.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'lr_init': 0.0005,
 'max_input_size': 1500,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_GL999Jul26\\Documentation_data-GL999_95shuffle1.pickle',
 'min_input_size': 64,
 'mirror': False,
 'multi_stage': False,
 'multi_step': [[0.005, 10000], [0.02, 15000], [0.002, 20000], [0.001, 30000]],
 'net_type': 'mobilenet_v2_1.0',
 'num_joints': 11,
 'optimizer': 'sgd',
 'pairwise_huber_loss': False,
 'pairwise_predict': False,
 'partaffinityfield_predict': False,
 'pos_dist_thresh': 17,
 'project_path': 'E:\\DLC\\GL999-sw-2021-07-26',
 'regularize': False,
 'rotation': 25,
 'rotratio': 0.4,
 'save_iters': 50000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'sharpen': False,
 'sharpenratio': 0.3,
 'shuffle': True,
 'snapshot_prefix': 'E:\\DLC\\GL999-sw-2021-07-26\\dlc-models\\iteration-0\\GL999Jul26-trainset95shuffle1\\train\\snapshot',
 'stride': 8.0,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Batch Size is 1
H:\anaconda3\envs\DLC2107\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py:1692: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
2021-07-28 14:32:59.268248: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library nvcuda.dll
2021-07-28 14:32:59.330934: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:18:00.0 name: NVIDIA GeForce RTX 3090 computeCapability: 8.6
coreClock: 1.695GHz coreCount: 82 deviceMemorySize: 24.00GiB deviceMemoryBandwidth: 871.81GiB/s
2021-07-28 14:32:59.331363: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudart64_110.dll
2021-07-28 14:32:59.368115: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cublas64_11.dll
2021-07-28 14:32:59.368321: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cublasLt64_11.dll
2021-07-28 14:32:59.377219: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cufft64_10.dll
2021-07-28 14:32:59.379276: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library curand64_10.dll
2021-07-28 14:32:59.385195: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cusolver64_11.dll
2021-07-28 14:32:59.391002: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cusparse64_11.dll
2021-07-28 14:32:59.392159: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudnn64_8.dll
2021-07-28 14:32:59.393123: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-07-28 14:32:59.396426: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-07-28 14:32:59.416132: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:18:00.0 name: NVIDIA GeForce RTX 3090 computeCapability: 8.6
coreClock: 1.695GHz coreCount: 82 deviceMemorySize: 24.00GiB deviceMemoryBandwidth: 871.81GiB/s
2021-07-28 14:32:59.422590: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-07-28 14:33:00.109666: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-07-28 14:33:00.109910: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
2021-07-28 14:33:00.113248: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
2021-07-28 14:33:00.114999: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 21670 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:18:00.0, compute capability: 8.6)
Loading ImageNet-pretrained mobilenet_v2_1.0
2021-07-28 14:33:00.562774: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:18:00.0 name: NVIDIA GeForce RTX 3090 computeCapability: 8.6
coreClock: 1.695GHz coreCount: 82 deviceMemorySize: 24.00GiB deviceMemoryBandwidth: 871.81GiB/s
2021-07-28 14:33:00.563277: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-07-28 14:33:00.568924: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-07-28 14:33:00.570582: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
2021-07-28 14:33:00.572561: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
2021-07-28 14:33:00.574836: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 21670 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:18:00.0, compute capability: 8.6)
Max_iters overwritten as 30000
Display_iters overwritten as 100
Save_iters overwritten as 15000
Training parameter:
{'stride': 8.0, 'weigh_part_predictions': False, 'weigh_negatives': False, 'fg_fraction': 0.25, 'mean_pixel': [123.68, 116.779, 103.939], 'shuffle': True, 'snapshot_prefix': 'E:\\DLC\\GL999-sw-2021-07-26\\dlc-models\\iteration-0\\GL999Jul26-trainset95shuffle1\\train\\snapshot', 'log_dir': 'log', 'global_scale': 0.8, 'location_refinement': True, 'locref_stdev': 7.2801, 'locref_loss_weight': 0.05, 'locref_huber_loss': True, 'optimizer': 'sgd', 'intermediate_supervision': False, 'intermediate_supervision_layer': 12, 'regularize': False, 'weight_decay': 0.0001, 'crop_pad': 0, 'scoremap_dir': 'test', 'batch_size': 1, 'dataset_type': 'imgaug', 'deterministic': False, 'mirror': False, 'pairwise_huber_loss': False, 'weigh_only_present_joints': False, 'partaffinityfield_predict': False, 'pairwise_predict': False, 'all_joints': [[0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [10]], 'all_joints_names': ['Red', 'LeftHead', 'LeftHand', 'LeftLeg', 'Nose', 'Back', 'Pelvis', 'Green', 'RightHead', 'RightHand', 'RightLeg'], 'alpha_r': 0.02, 'clahe': True, 'claheratio': 0.1, 'cropratio': 0.4, 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_GL999Jul26\\GL999_sw95shuffle1.mat', 'decay_steps': 30000, 'display_iters': 1000, 'edge': False, 'emboss': {'alpha': [0.0, 1.0], 'embossratio': 0.1, 'strength': [0.5, 1.5]}, 'histeq': True, 'histeqratio': 0.1, 'init_weights': 'H:\\anaconda3\\envs\\DLC2107\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\mobilenet_v2_1.0_224.ckpt', 'lr_init': 0.0005, 'max_input_size': 1500, 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_GL999Jul26\\Documentation_data-GL999_95shuffle1.pickle', 'min_input_size': 64, 'multi_stage': False, 'multi_step': [[0.005, 10000], [0.02, 15000], [0.002, 20000], [0.001, 30000]], 'net_type': 'mobilenet_v2_1.0', 'num_joints': 11, 'pos_dist_thresh': 17, 'project_path': 'E:\\DLC\\GL999-sw-2021-07-26', 'rotation': 25, 'rotratio': 0.4, 'save_iters': 50000, 'scale_jitter_lo': 0.5, 'scale_jitter_up': 1.25, 'sharpen': False, 'sharpenratio': 0.3, 'covering': True, 'elastic_transform': True, 'motion_blur': True, 'motion_blur_params': {'k': 7, 'angle': (-90, 90)}}
Starting training....
```

config file:
```
    # Project definitions (do not edit)
Task: GL999
scorer: sw
date: Jul26
multianimalproject: false
identity:

    # Project path (change when moving around)
project_path: E:\DLC\GL999-sw-2021-07-26

    # Annotation data set configuration (and individual video cropping parameters)
video_sets:
  E:\DLC\GL999-sw-2021-07-26\videos\GL999_circl1_cam1_20210708_112_4k.avi:
    crop: 1164, 3317, 115, 2391
  E:\DLC\GL999-sw-2021-07-26\videos\GL999_circle1_cam1_2021-07-11-10-50-49_112_4k.avi:
    crop: 1164, 3317, 115, 2391
  E:\DLC\GL999-sw-2021-07-26\videos\GL999_circle2_cam1_2021-07-08-11-32-32_112_4k.avi:
    crop: 1164, 3317, 115, 2391
  E:\DLC\GL999-sw-2021-07-26\videos\GL999_circle2_cam1_2021-07-11-10-50-49_112_4k.avi:
    crop: 1164, 3317, 115, 2391
  E:\DLC\GL999-sw-2021-07-26\videos\GL999_circle3_cam1_2021-07-08-11-32-32_112_4k.avi:
    crop: 1164, 3317, 115, 2391
  E:\DLC\GL999-sw-2021-07-26\videos\GL999_circle3_cam1_2021-07-11-10-50-49_112_4k.avi:
    crop: 1164, 3317, 115, 2391
bodyparts:
- Red
- LeftHead
- LeftHand
- LeftLeg
- Nose
- Back
- Pelvis
- Green
- RightHead
- RightHand
- RightLeg

start: 0.4
stop: 0.6
numframes2pick: 20

    # Plotting configuration
skeleton:
skeleton_color: black
pcutoff: 0.6
dotsize: 20
alphavalue: 0.6
colormap: jet

    # Training,Evaluation and Analysis configuration
TrainingFraction:
- 0.95
iteration: 0
default_net_type: efficientnet-b0
default_augmenter: default
snapshotindex: -1
batch_size: 8

    # Cropping Parameters (for analysis and outlier frame detection)
cropping: true
croppedtraining: true
    #if cropping is true for analysis, then set the values here:
x1: 1164
x2: 3317
y1: 115
y2: 2391

    # Refinement configuration (parameters from annotation dataset configuration also relevant in this stage)
corner2move2:
- 0
- 0
move2corner: true
```

training pose_cfg file:
```
all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
- - 8
- - 9
- - 10
all_joints_names:
- Red
- LeftHead
- LeftHand
- LeftLeg
- Nose
- Back
- Pelvis
- Green
- RightHead
- RightHand
- RightLeg
alpha_r: 0.02
batch_size: 1
clahe: true
claheratio: 0.1
cropratio: 0.4
dataset: training-datasets\iteration-0\UnaugmentedDataSet_GL999Jul26\GL999_sw95shuffle1.mat
dataset_type: imgaug
decay_steps: 30000
display_iters: 1000
edge: false
emboss:
  alpha:
  - 0.0
  - 1.0
  embossratio: 0.1
  strength:
  - 0.5
  - 1.5
global_scale: 0.8
histeq: true
histeqratio: 0.1
init_weights: H:\anaconda3\envs\DLC2107\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\mobilenet_v2_1.0_224.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 0.0005
max_input_size: 1500
metadataset: training-datasets\iteration-0\UnaugmentedDataSet_GL999Jul26\Documentation_data-GL999_95shuffle1.pickle
min_input_size: 64
mirror: false
multi_stage: false
multi_step:
- - 0.005
  - 10000
- - 0.02
  - 15000
- - 0.002
  - 20000
- - 0.001
  - 30000
net_type: mobilenet_v2_1.0
num_joints: 11
pairwise_huber_loss: false
pairwise_predict: false
partaffinityfield_predict: false
pos_dist_thresh: 17
project_path: E:\DLC\GL999-sw-2021-07-26
rotation: 25
rotratio: 0.4
save_iters: 50000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
sharpen: false
sharpenratio: 0.3
```

### Relevant log output

```shell
2021-07-28 14:32:56 Config:
{'all_joints': [[0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [10]],
 'all_joints_names': ['Red',
                      'LeftHead',
                      'LeftHand',
                      'LeftLeg',
                      'Nose',
                      'Back',
                      'Pelvis',
                      'Green',
                      'RightHead',
                      'RightHand',
                      'RightLeg'],
 'alpha_r': 0.02,
 'batch_size': 1,
 'clahe': True,
 'claheratio': 0.1,
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_GL999Jul26\\GL999_sw95shuffle1.mat',
 'dataset_type': 'imgaug',
 'decay_steps': 30000,
 'deterministic': False,
 'display_iters': 1000,
 'edge': False,
 'emboss': {'alpha': [0.0, 1.0], 'embossratio': 0.1, 'strength': [0.5, 1.5]},
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'histeq': True,
 'histeqratio': 0.1,
 'init_weights': 'H:\\anaconda3\\envs\\DLC2107\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\mobilenet_v2_1.0_224.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'lr_init': 0.0005,
 'max_input_size': 1500,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_GL999Jul26\\Documentation_data-GL999_95shuffle1.pickle',
 'min_input_size': 64,
 'mirror': False,
 'multi_stage': False,
 'multi_step': [[0.005, 10000], [0.02, 15000], [0.002, 20000], [0.001, 30000]],
 'net_type': 'mobilenet_v2_1.0',
 'num_joints': 11,
 'optimizer': 'sgd',
 'pairwise_huber_loss': False,
 'pairwise_predict': False,
 'partaffinityfield_predict': False,
 'pos_dist_thresh': 17,
 'project_path': 'E:\\DLC\\GL999-sw-2021-07-26',
 'regularize': False,
 'rotation': 25,
 'rotratio': 0.4,
 'save_iters': 50000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'sharpen': False,
 'sharpenratio': 0.3,
 'shuffle': True,
 'snapshot_prefix': 'E:\\DLC\\GL999-sw-2021-07-26\\dlc-models\\iteration-0\\GL999Jul26-trainset95shuffle1\\train\\snapshot',
 'stride': 8.0,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)
