### ISSUE TITLE
cropping video problem and an error during "refine tracklet"

### ISSUE THREAD

**Issue by deepbraincut** [DeepLabCut/DeepLabCut#1458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi,

First, thank you so much for the awesome work! I think the problems I am experiencing probably came from misuses of the program OR some necessary processes have not been done properly, but I could not figure out by online searching. so if you can advice me which points I did wrong, it would be really appreciate!

I am tracking 2 mice in the home cage, and upgrade to DLC2.2 from DLC2.2rc3 yesterday (yay!). I labeled and trained with new version, and the new training went well. I ran evaluation and it seems fine. But I have 2 problems here.

1. I analyzed some videos and found the outside of the cropped area were detected, even after I changed the config file cropping parameter. 
```
    # Cropping Parameters (for analysis and outlier frame detection)
cropping: true
    #if cropping is true for analysis, then set the values here:
x1: 100
x2: 520
y1: 150
y2: 360
```
So I used video editor tap to crop the video and got the error message like this: 
‘ffmpeg’ is not recognized as an internal or external command,
operable program or batch file.’

what am I missing here? 

2. The second problem happens when I tried to refine the tracklets.  but have an error message “FileNotFoundError: File does not exist” 
What I did: load the config file > go to refine tracklets > step1: create tracks > step2: optional refine tracks
I didn’t change any default values in refine tracks tap (maybe that’s why?)

I still could analyze the video but couldn’t go further steps: create video or refine labels.

I would appreciate any help!!!!

-Ain

### Operating System

operating system

Windows 10

### DeepLabCut version

dlc version
DLC 2.2

### DeepLabCut mode

multi animal

### Device type

gpu
NVIDIA GeForce RTX 2060 super

### Steps To Reproduce

1. in the anaconda3 env, activate DLC-GPU and ran deeplabcut 2.2
2. ran this config file
```
    # Project definitions (do not edit)
Task: SRM_STIM_2mice
scorer: ac
date: Jul26
multianimalproject: true
identity: true

    # Project path (change when moving around)
project_path: D:\DLC\SRM_STIM_2mice-ac-2021-07-26

    # Annotation data set configuration (and individual video cropping parameters)
video_sets:
  D:\DLC\SRM_STIM_2mice-ac-2021-07-26\videos\Trial1_2021-06-25-094507-0000.avi:
    crop: 99, 536, 145, 399
  D:\DLC\SRM_STIM_2mice-ac-2021-07-26\videos\Trial2_2021-06-25-095115-0000.avi:
    crop: 103, 521, 149, 406
  D:\DLC\SRM_STIM_2mice-ac-2021-07-26\videos\Trial3_2021-06-25-095713-0000.avi:
    crop: 94, 519, 140, 408
  D:\DLC\SRM_STIM_2mice-ac-2021-07-26\videos\Trial4_2021-06-25-100315-0000.avi:
    crop: 0, 640, 0, 480
  D:\DLC\SRM_STIM_2mice-ac-2021-07-26\videos\Trial5_2021-06-25-100916-0000.avi:
    crop: 0, 640, 0, 480
  D:\DLC\SRM_STIM_2mice-ac-2021-07-26\videos\Trial6_2021-06-25-101515-0000.avi:
    crop: 79, 533, 133, 403
  D:\DLC\SRM_STIM_2mice-ac-2021-07-26\videos\Trial7_2021-06-25-102121-0000.avi:
    crop: 80, 534, 138, 406
  D:\DLC\SRM_STIM_2mice-ac-2021-07-26\videos\Trial8_2021-06-25-102721-0000.avi:
    crop: 75, 534, 132, 401
  D:\DLC\SRM_STIM_2mice-ac-2021-07-26\videos\Trial9_2021-06-25-103329-0000.avi:
    crop: 97, 532, 135, 396
  D:\DLC\SRM_STIM_2mice-ac-2021-07-26\videos\Trial10_2021-06-25-103932-0000.avi:
    crop: 76, 532, 131, 399
  D:\DLC\SRM_STIM_2mice-ac-2021-07-26\videos\Trial1_2021-07-17-095318-0000.avi:
    crop: 77, 498, 96, 349
  D:\DLC\SRM_STIM_2mice-ac-2021-07-26\videos\Trial2_2021-07-17-095936-0000.avi:
    crop: 69, 496, 96, 362
  D:\DLC\SRM_STIM_2mice-ac-2021-07-26\videos\Trial3_2021-07-17-100537-0000.avi:
    crop: 61, 522, 108, 368
  D:\DLC\SRM_STIM_2mice-ac-2021-07-26\videos\Trial4_2021-07-17-101145-0000.avi:
    crop: 0, 640, 0, 480
  D:\DLC\SRM_STIM_2mice-ac-2021-07-26\videos\Trial5_2021-07-17-101759-0000.avi:
    crop: 0, 640, 0, 480
  D:\DLC\SRM_STIM_2mice-ac-2021-07-26\videos\Trial6_2021-07-17-102400-0000.avi:
    crop: 49, 501, 94, 379
  D:\DLC\SRM_STIM_2mice-ac-2021-07-26\videos\Trial7_2_2021-07-17-103323-0000.avi:
    crop: 67, 515, 93, 385
  D:\DLC\SRM_STIM_2mice-ac-2021-07-26\videos\Trial7_2021-07-17-103008-0000.avi:
    crop: 64, 504, 91, 375
  D:\DLC\SRM_STIM_2mice-ac-2021-07-26\videos\Trial8_2021-07-17-103618-0000.avi:
    crop: 66, 504, 75, 356
  D:\DLC\SRM_STIM_2mice-ac-2021-07-26\videos\Trial9_2021-07-17-104211-0000.avi:
    crop: 58, 503, 83, 360
  D:\DLC\SRM_STIM_2mice-ac-2021-07-26\videos\Trial10_2021-07-17-104805-0000.avi:
    crop: 61, 507, 76, 356
individuals:
- Test
- Sample

uniquebodyparts: []
multianimalbodyparts:
- Nose
- LeftEar
- RightEar
- Center
- LeftLeg
- RightLeg
- Tail
skeleton:
- - LeftEar
  - Center
- - RightLeg
  - Tail
- - Nose
  - RightEar
- - LeftEar
  - Tail
- - RightEar
  - RightLeg
- - Nose
  - Center
- - LeftEar
  - RightEar
- - LeftEar
  - RightLeg
- - Center
  - Tail
- - Nose
  - LeftLeg
- - RightEar
  - Tail
- - LeftLeg
  - RightLeg
- - LeftEar
  - LeftLeg
- - RightEar
  - Center
- - Center
  - RightLeg
- - Nose
  - LeftEar
- - LeftLeg
  - Tail
- - Center
  - LeftLeg
- - RightEar
  - LeftLeg
bodyparts: MULTI!
start: 0
stop: 1
numframes2pick: 20

    # Plotting configuration
skeleton_color: black
pcutoff: 0.6
dotsize: 12
alphavalue: 0.7
colormap: rainbow

    # Training,Evaluation and Analysis configuration
TrainingFraction:
- 0.95
iteration: 0
default_net_type: dlcrnet_ms5
default_augmenter: multi-animal-imgaug
snapshotindex: -1
batch_size: 8

    # Cropping Parameters (for analysis and outlier frame detection)
cropping: true
    #if cropping is true for analysis, then set the values here:
x1: 100
x2: 520
y1: 150
y2: 360

    # Refinement configuration (parameters from annotation dataset configuration also relevant in this stage)
corner2move2:
- 50
- 50
move2corner: true
croppedtraining: false
```
3. 
1) load the config file> go to video editor> set cropping boundary in the popup window> click CROP> error like: ‘ffmpeg’ is not recognized as an internal or external command, operable program or batch file.’

2) load the config file > go to refine tracklets > step1: create tracks > step2: optional refine tracks> got an error message ' filenotfounderror' (see below)  

### Relevant log output

```shell
(DLC-GPU) C:\Users\sahay>python -m deeplabcut
2021-08-10 10:15:23.242303: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudart64_110.dll
Starting GUI…
currently DLCRNet is only supported in multi-animal mode
Processing… D:\DLC\SRM_STIM_2mice-ac-2021-07-26\videos\Trial1_2021-06-25-094507-0000.avi
D:\DLC\SRM_STIM_2mice-ac-2021-07-26\videos already exists!
100%|█████████████████████████████████████████████████████████████████████████████████| 21/21 [00:00<00:00, 263.20it/s]
Traceback (most recent call last):
File “C:\Users\sahay\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\gui\refine_tracklets.py”, line 319, in refine_tracklets
max_gap=self.slider_gap.GetValue(),
File “C:\Users\sahay\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\gui\tracklet_toolbox.py”, line 793, in refine_tracklets
manager.load_tracklets_from_hdf(pickle_or_h5_file)
File “C:\Users\sahay\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\refine_training_dataset\tracklets.py”, line 238, in load_tracklets_from_hdf
df = pd.read_hdf(filename)
File “C:\Users\sahay\Anaconda3\envs\DLC-GPU\lib\site-packages\pandas\io\pytables.py”, line 387, in read_hdf
raise FileNotFoundError(f"File {path_or_buf} does not exist")
FileNotFoundError: File does not exist
```

### Anything else?

![crop error](https://user-images.githubusercontent.com/75436015/129043960-b9927c58-7132-48f6-9435-f5f42d120d9c.PNG)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)
