### ISSUE TITLE
save_as_csv=True not working if auto_track=False, and/or disappearing bodyparts

### ISSUE THREAD

**Issue by Hierakonpolis** [DeepLabCut/DeepLabCut#2008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I am attempting to label my videos using, in a multi animal project:

`deeplabcut.analyze_videos(config_path, test_vids, auto_track=False, save_as_csv=True)`

What I would like to have is the csv carrying the same information included in the video generated through the GUI with _Create video for checking detection_ as _Yes_.

Using auto_track=True seems to simply remove most body parts from the .csv and replace them with empty columns (which are visible and ok in the video created for detection via the GUI, but still not present in the generated .csv.). I need to either skip this this step entirely, or somehow stop losing these body parts. Setting the p cutoff to 0 and/or checking the unfiltered csv generated through the GUI does not seem to solve the problem.

Is this intended behavior, and are there ways around it? Is this related to me having added more body parts in the latest iteration?

### Operating System

Linux Mint 20.3

### DeepLabCut version

dlc version = 2.2.2

### DeepLabCut mode

multi animal

### Device type

NVIDIA RTX A4000

### Steps To Reproduce

I am really just running 
`deeplabcut.analyze_videos(config_path, test_vids, auto_track=False, save_as_csv=True)`

The config file::
```

    # Project definitions (do not edit)
Task: project_title
scorer: me
date: Sep30
multianimalproject: true
identity: false

    # Project path (change when moving around)
project_path: /media/DATA/DLCmodel/project_title-me-2022-09-30

    # Annotation data set configuration (and individual video cropping parameters)
video_sets:
  /media/DATA/Test 2 Video 1.avi:
    crop: 0, 1280, 0, 1024
  /media/DATA/Test 1 Video 1.avi:
    crop: 0, 1280, 0, 1024
individuals:
- Mouse1
- Mouse2
uniquebodyparts: []
multianimalbodyparts:
- Nose
- Head
- TailBase
- Center
- Upperback
- Lowerback
- Upperback+
- Upperback-
- Lowerback+
- Lowerback-
- LeftEar
- RightEar
bodyparts: MULTI!

    # Fraction of video to start/stop when extracting frames for labeling/refinement
start: 0
stop: 1
numframes2pick: 30

    # Plotting configuration
skeleton:
- - Nose
  - Head
- - Center
  - Lowerback+
- - Lowerback
  - Lowerback+
- - Head
  - RightEar
- - Center
  - Upperback-
- - Upperback
  - Upperback+
- - TailBase
  - Lowerback-
- - Head
  - LeftEar
- - Lowerback
  - Lowerback-
- - Head
  - Upperback+
- - Upperback
  - Upperback-
skeleton_color: black
pcutoff: 0.6
dotsize: 4
alphavalue: 0.7
colormap: rainbow

    # Training,Evaluation and Analysis configuration
TrainingFraction:
- 0.95
iteration: 1
default_net_type: dlcrnet_ms5
default_augmenter: multi-animal-imgaug
default_track_method: ellipse
snapshotindex: 45
batch_size: 8

    # Cropping Parameters (for analysis and outlier frame detection)
cropping: false
    #if cropping is true for analysis, then set the values here:
x1: 0
x2: 640
y1: 277
y2: 624

    # Refinement configuration (parameters from annotation dataset configuration also relevant in this stage)
corner2move2:
- 50
- 50
move2corner: true
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)
