### ISSUE TITLE
`create_labeled_video`  passed input `displayedbodyparts` list not plotting all items

### ISSUE THREAD

**Issue by MMathisLab** [DeepLabCut/DeepLabCut#2269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When I run `deeplabcut.create_labeled_video(path_config_file,videofile_path, displayedbodyparts=['zero','one','two','three','four'])` only part `zero` is displayed on the output video, whereas all 5 items should be displayed.

This is a new behavior that is changed; perhaps in matplotlib? I am using version `3.7.1`

### Operating System

linux (colab)

### DeepLabCut version

2.3.5

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

import latest DLC, try to create a labeled video with specific keypoints only (not 'all')

### Anything else?

thanks @n-poulsen !

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
I was not able to replicate this issue on a single animal project on Google Colab with the configuration file:

```yaml
...
bodyparts:
- nose
- leftFoot
- rightFoot

skeleton:
- - nose
  - leftFoot
- - nose
  - rightFoot

skeleton_color: black
pcutoff: 0.6
dotsize: 12
alphavalue: 0.7
colormap: rainbow
...
```
and the code
```python
import deeplabcut
path_config_file = "/content/drive/MyDrive/test/config.yaml"
videofile_path = "/content/drive/MyDrive/test/videos/dog_clip.avi"
deeplabcut.create_labeled_video(
    path_config_file,
    videofile_path,
    displayedbodyparts=['leftFoot', 'rightFoot'],
    videotype="avi",
    draw_skeleton=True,
)
```

While all of the selected bodyparts were plotted correctly, the entire skeleton was displayed. The method should adapt to only plot segments for which both ends are in the `displayedbodyparts` list.

Edit:
The issue with skeleton plotting was fixed by #2274
