### ISSUE TITLE
Evaluate GUI feature bug/error

### ISSUE THREAD

**Issue by bainro** [DeepLabCut/DeepLabCut#2505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I've tried installing DLC 2.3.8 several times on my Wins10 machine with a GPU, but no luck. Installed with conda. Run the GUI and then evaluate feature breaks (see attached photo).

Evaluation works when running this simple script though:

```
import os
import deeplabcut

os.rmdir(r'C:\Users\jshobe\Desktop\DLC_TR\TreadmillVR-Winny-2023-11-16\evaluation-results\iteration-0')
conf_path = r"C:\Users\jshobe\Desktop\DLC_TR\TreadmillVR-Winny-2023-11-16\config.yaml"
deeplabcut.evaluate_network(conf_path, plotting=True)
```

![image](https://github.com/DeepLabCut/DeepLabCut/assets/31903812/33414ca6-13ec-446a-a1cf-05b8d9f1e715)

Here's our config.yaml:

```yaml
    # Project definitions (do not edit)
Task: TreadmillVR
scorer: Winny
date: Nov16
multianimalproject: false
identity:

    # Project path (change when moving around)
project_path: C:/Users/jshobe/Desktop/DLC_TR/TreadmillVR-Winny-2023-11-16

    # Annotation data set configuration (and individual video cropping parameters)
video_sets:
  C:\Users\jshobe\Desktop\DLC_TR\TreadmillVR-Winny-2023-11-16\videos\TR8_Rec_2-22-2023_2023_02_22__15_37_47.avi:
    crop: 0, 644, 0, 484
bodyparts:
- Paw1C
- Paw1F1
- Paw1F2
- Paw1F3
- Paw1F4
- Paw1F5
- Paw2C
- Paw2F1
- Paw2F2
- Paw2F3
- Paw2F4
- Paw2F5
- BPawC
- BPawF1
- BPawF2
- BPawF3
- BPawF4
- BPawF5
- Tongue

    # Fraction of video to start/stop when extracting frames for labeling/refinement
start: 0
stop: 1
numframes2pick: 20

    # Plotting configuration
skeleton:
- - bodypart1
  - bodypart0
- - objectA
  - bodypart3
skeleton_color: black
pcutoff: 0.6
dotsize: 10
alphavalue: 0.7
colormap: rainbow

    # Training,Evaluation and Analysis configuration
TrainingFraction:
- 0.95
iteration: 0
default_net_type: resnet_50
default_augmenter: default
snapshotindex: -1
batch_size: 8

    # Cropping Parameters (for analysis and outlier frame detection)
cropping: false
    #if cropping is true for analysis, then set the values here:
x1: 0
x2: 640
y1: 277
y2: 624

    # Refinement configuration (parameters from annotation dataset configuration also relevant in this stage)
corner2move2:
- 50
- 50
move2corner: true
```

### Operating System

windows 10

### DeepLabCut version

2.3.8

### DeepLabCut mode

single animal

### Device type

TITAX Xp

### Steps To Reproduce

1. See main text, cheers

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)
