### ISSUE TITLE
No unfiltered data file found

### ISSUE THREAD

**Issue by vknorman** [DeepLabCut/DeepLabCut#2562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I trained a new model for DLC and used it to analyze a video. After it finished analyzing the video, I received this error:
No unfiltered data file found in /media/antonio/Elements1/Batch 2 DLC/1865_1203_done(body) for video face-12032022133624-0000_cropped and scorer DLC_resnet50_Data2_faceApril24shuffle1_500000.
Traceback (most recent call last):

### Operating System

Ubuntu

### DeepLabCut version

python 3.8

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

```yaml
  # Project definitions (do not edit)
Task: Data2_face
scorer: Shew
date: April24
multianimalproject: false
identity:

    # Project path (change when moving around)
project_path: /home/antonio/Shew Face 2024-Shew lab-2024-04-17

    # Annotation data set configuration (and individual video cropping parameters)
video_sets:
  /media/antonio/Elements1/Batch 2 DLC/1865_1203_done(body)/face-12032022133624-0000_cropped.mp4:
    crop: 0, 1200, 0, 1000
bodyparts:
- n1
- n2
- n3
- n4
- w1
- w2
- w3
- w4
- p1
- p2
- p3
- p4
- p5
- p6
- p7
- p8

    # Fraction of video to start/stop when extracting frames for labeling/refinement
start: 0
stop: 1
numframes2pick: 200

    # Plotting configuration
skeleton:
- - n1
  - n2
- - n2
  - n3
- - n3
  - n4
- - n4
  - n1
- - w1
  - w2
- - w2
  - w3
- - w3
  - w4
- - w4
  - w1
- - p1
  - p2
- - p2
  - p3
- - p3
  - p4
- - p4
  - p5
- - p5
  - p6
- - p6
  - p7
- - p7
  - p8
- - p8
  - p1
skeleton_color: black
pcutoff: 0.6
dotsize: 12
alphavalue: 0.7
colormap: rainbow

    # Training,Evaluation and Analysis configuration
TrainingFraction:
- 0.95
iteration: 0
default_net_type: resnet_50
default_augmenter: default
snapshotindex: -1
batch_size: 8

    # Cropping Parameters (for analysis and outlier frame detection)
cropping: false
    #if cropping is true for analysis, then set the values here:
x1: 0
x2: 640
y1: 277
y2: 624

    # Refinement configuration (parameters from annotation dataset configuration also relevant in this stage)
corner2move2:
- 50
- 50
move2corner: true
```

### Relevant log output

```shell
No unfiltered data file found in /media/antonio/Elements1/Batch 2 DLC/1865_1203_done(body) for video face-12032022133624-0000_cropped and scorer DLC_resnet50_Data2_faceApril24shuffle1_500000.
Traceback (most recent call last):
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)
