### ISSUE TITLE
DLC2.3.10 cannot create video after analysing 

### ISSUE THREAD

**Issue by Aaronself** [DeepLabCut/DeepLabCut#2661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Main Problem Description

hi, I have a problem when i try to create video from DLC.2.3.10, the cmd and the GUI show the below 

`FileNotFoundError: [WinError 3] : 'C:/Users/86539/Desktop/test-rat_first_test-2024-07-09\\dlc-models\\iteration-0\\testJul9-trainset95shuffle2\\train`

![image](https://github.com/DeepLabCut/DeepLabCut/assets/52153251/ab02cd76-884c-4916-8b21-2e69a7f58f3e)

actually i didn't know why the dir can be `/` at first and then use the `\\`

when i try to anthor cmd window and try to test the object file

![image](https://github.com/DeepLabCut/DeepLabCut/assets/52153251/e491968e-d0f6-4d0d-9fca-9f769e8eb36b)

so maybe its different dir format be the problem? 

### A little other problem

After training the network, it throws a exception

![image](https://github.com/DeepLabCut/DeepLabCut/assets/52153251/1f01bddc-76ed-478c-b6c7-c110edf67c54)

i didn't know whats wrong but it seems like that the evalutae can be done

thanks for your help and message !!

### Operating System

operating system: Windows

### DeepLabCut version

dlc version:

DLC.2.3.10

### DeepLabCut mode

single animal

### Device type

RTX4060

## python version

python 3.10.14 

```
absl-py                       2.1.0
alabaster                     0.7.16
app-model                     0.2.7
appdirs                       1.4.4
asttokens                     2.4.1
astunparse                    1.6.3
attrs                         23.2.0
Babel                         2.15.0
blosc2                        2.0.0
build                         1.2.1
cachetools                    5.3.3
cachey                        0.2.1
certifi                       2024.7.4
charset-normalizer            3.3.2
click                         8.1.7
cloudpickle                   3.0.0
colorama                      0.4.6
comm                          0.2.2
contourpy                     1.2.1
cycler                        0.12.1
Cython                        3.0.10
dask                          2024.7.0
dask-expr                     1.1.7
dask-image                    2024.5.3
debugpy                       1.8.2
decorator                     5.1.1
deeplabcut                    2.3.10
dlclibrary                    0.0.6
docstring_parser              0.16
docutils                      0.17.1
exceptiongroup                1.2.1
executing                     2.0.1
filelock                      3.13.1
filterpy                      1.4.5
flatbuffers                   24.3.25
flexcache                     0.3
flexparser                    0.3.1
fonttools                     4.53.1
freetype-py                   2.4.0
fsspec                        2024.2.0
gast                          0.4.0
google-auth                   2.32.0
google-auth-oauthlib          0.4.6
google-pasta                  0.2.0
grpcio                        1.64.1
h5py                          3.11.0
HeapDict                      1.0.1
hsluv                         5.0.4
huggingface-hub               0.23.4
idna                          3.7
imageio                       2.34.2
imageio-ffmpeg                0.5.1
imagesize                     1.4.1
imgaug                        0.4.0
importlib_metadata            8.0.0
in-n-out                      0.2.1
intel-openmp                  2021.4.0
ipykernel                     6.29.5
ipython                       8.26.0
jedi                          0.19.1
Jinja2                        3.1.3
joblib                        1.4.2
jsonschema                    4.23.0
jsonschema-specifications     2023.12.1
jupyter_client                8.6.2
jupyter_core                  5.7.2
keras                         2.10.0
Keras-Preprocessing           1.1.2
kiwisolver                    1.4.5
lazy_loader                   0.4
libclang                      18.1.1
llvmlite                      0.43.0
locket                        1.0.0
magicgui                      0.8.3
Markdown                      3.6
markdown-it-py                3.0.0
MarkupSafe                    2.1.5
matplotlib                    3.8.4
matplotlib-inline             0.1.7
mdurl                         0.1.2
mkl                           2021.4.0
mkl-fft                       1.3.8
mkl-random                    1.2.4
mkl-service                   2.4.0
mpmath                        1.3.0
msgpack                       1.0.8
msgpack-numpy                 0.4.8
napari                        0.4.18
napari-console                0.0.9
napari-deeplabcut             0.2.1.7
napari-plugin-engine          0.2.0
napari-svg                    0.2.0
natsort                       8.4.0
ndindex                       1.8
nest-asyncio                  1.6.0
networkx                      3.2.1
npe2                          0.7.6
numba                         0.60.0
numexpr                       2.10.1
numpy                         1.24.1
numpydoc                      1.5.0
oauthlib                      3.2.2
opencv-python                 4.10.0.84
opencv-python-headless        4.10.0.84
opt-einsum                    3.3.0
packaging                     24.1
pandas                        2.2.2
parso                         0.8.4
partd                         1.4.2
patsy                         0.5.6
Pillow                        9.5.0
PIMS                          0.7
Pint                          0.24.1
pip                           24.0
platformdirs                  4.2.2
pooch                         1.8.2
prompt_toolkit                3.0.47
protobuf                      3.19.6
psutil                        6.0.0
psygnal                       0.11.1
pure-eval                     0.2.2
py-cpuinfo                    9.0.0
pyarrow                       16.1.0
pyasn1                        0.6.0
pyasn1_modules                0.4.0
pyconify                      0.1.6
pydantic                      1.10.17
pydantic-compat               0.1.2
Pygments                      2.18.0
PyOpenGL                      3.1.7
pyparsing                     3.1.2
pyproject_hooks               1.1.0
PySide6                       6.4.2
PySide6-Addons                6.4.2
PySide6-Essentials            6.4.2
python-dateutil               2.9.0.post0
pytz                          2024.1
pywin32                       306
PyYAML                        6.0.1
pyzmq                         26.0.3
QDarkStyle                    3.1
qtconsole                     5.5.2
QtPy                          2.4.1
referencing                   0.35.1
requests                      2.32.3
requests-oauthlib             2.0.0
rich                          13.7.1
rpds-py                       0.19.0
rsa                           4.9
ruamel.yaml                   0.18.6
ruamel.yaml.clib              0.2.8
scikit-image                  0.24.0
scikit-learn                  1.5.1
scipy                         1.14.0
setuptools                    69.5.1
shapely                       2.0.4
shellingham                   1.5.4
shiboken6                     6.4.2
six                           1.16.0
slicerator                    1.1.0
snowballstemmer               2.2.0
Sphinx                        4.5.0
sphinxcontrib-applehelp       1.0.8
sphinxcontrib-devhelp         1.0.6
sphinxcontrib-htmlhelp        2.0.5
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.7
sphinxcontrib-serializinghtml 1.1.10
stack-data                    0.6.3
statsmodels                   0.14.2
superqt                       0.6.7
sympy                         1.12
tables                        3.8.0
tabulate                      0.9.0
tbb                           2021.11.0
tensorboard                   2.10.1
tensorboard-data-server       0.6.1
tensorboard-plugin-wit        1.8.1
tensorflow                    2.10.0
tensorflow-estimator          2.10.0
tensorflow-io-gcs-filesystem  0.31.0
tensorpack                    0.11
termcolor                     2.4.0
tf-slim                       1.1.0
threadpoolctl                 3.5.0
tifffile                      2024.7.2
tomli                         2.0.1
tomli_w                       1.0.0
toolz                         0.12.1
torch                         2.3.1+cu118
torchaudio                    2.3.1+cu118
torchvision                   0.18.1+cu118
tornado                       6.4.1
tqdm                          4.66.4
traitlets                     5.14.3
typer                         0.12.3
typing_extensions             4.9.0
tzdata                        2024.1
urllib3                       2.2.2
vispy                         0.12.2
wcwidth                       0.2.13
Werkzeug                      3.0.3
wheel                         0.43.0
wrapt                         1.16.0
wxPython                      4.2.1
zipp                          3.19.2
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by Aaronself** [comment]
Attach the screenshot after clicking create video

![image](https://github.com/DeepLabCut/DeepLabCut/assets/52153251/6b46c177-407d-47ad-aaa9-6c3758fce32e)

**Comment by n-poulsen** [comment]
Hi @Aaronself! Could you please share the `config.yaml` file for your project? Indeed it seems that there's an error with the path format

**Comment by Aaronself** [comment]
> Hi @Aaronself! Could you please share the `config.yaml` file for your project? Indeed it seems that there's an error with the path format

Hi @n-poulsen, Thank you for your reply, it is the `config.yaml`

I find that when i load the project path, `project_path` will be changed. 

I only change the bodyparts and skeleton compared to the template

# config.yaml
```
## Project definitions (do not edit)
Task: rat_video
scorer: rat_test
date: Jul12
multianimalproject: false
identity:

## Project path (change when moving around)
project_path: C:/Users/86539/Desktop/rat_video_test/rat_video-rat_test-2024-07-12

## Annotation data set configuration (and individual video cropping parameters)
video_sets:
  C:\Users\86539\Desktop\rat_video_test\rat_video-rat_test-2024-07-12\videos\output_2024_07_09_20_24_02.avi:
    crop: 0, 410, 0, 420
  C:\Users\86539\Desktop\rat_video_test\rat_video-rat_test-2024-07-12\videos\output_2024_07_09_20_32_43.avi:
    crop: 0, 410, 0, 430
bodyparts:
- head
- body
- tail

## Fraction of video to start/stop when extracting frames for labeling/refinement

## Fraction of video to start/stop when extracting frames for labeling/refinement
start: 0
stop: 1
numframes2pick: 20

## Plotting configuration
skeleton:
- - head
  - body
- - body
  - tail
skeleton_color: black
pcutoff: 0.6
dotsize: 12
alphavalue: 0.7
colormap: rainbow

## Training,Evaluation and Analysis configuration
TrainingFraction:
- 0.95
iteration: 0
default_net_type: resnet_50
default_augmenter: default
snapshotindex: -1
batch_size: 8

## Cropping Parameters (for analysis and outlier frame detection)
cropping: false
##if cropping is true for analysis, then set the values here:
x1: 0
x2: 640
y1: 277
y2: 624

## Refinement configuration (parameters from annotation dataset configuration also relevant in this stage)
corner2move2:
- 50
- 50
move2corner: true
```
