### ISSUE TITLE
RuntimeError in DataLoader: Stack Expects Each Tensor to Be Equal Size During Training

### ISSUE THREAD

**Issue by Chap5732** [DeepLabCut/DeepLabCut#2728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

My training dataset consists of 338 images with 1-10 mice, 6 bodyparts were annotated.
(nose, left_ear, right_ear, mid_back, mouse_center and tail1, just the name I set, they are not truly the case as in superanimal model according to the result showed in confusion_matrix.png)

And I wanted to use a superanimal pretrained model (sa-tvm, 27 kpts) to fine-tune on my data(6 kpts) and I got error as follows:
`Traceback (most recent call last):
  File "/ssd01/user_acc_data/oppa/deeplabcut/code/satvm_training.py", line 29, in <module>
    main()
  File "/ssd01/user_acc_data/oppa/deeplabcut/code/satvm_training.py", line 26, in main
    train_network(config_path, shuffle, device, net_type)
  File "/ssd01/user_acc_data/oppa/deeplabcut/code/satvm_training.py", line 6, in train_network
    deeplabcut.train_network(
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/compat.py", line 245, in train_network
    return train_network(
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/apis/train.py", line 326, in train_network
    train(
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/apis/train.py", line 189, in train
    runner.fit(
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/runners/train.py", line 170, in fit
    train_loss = self._epoch(
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/runners/train.py", line 220, in _epoch
    for i, batch in enumerate(loader):
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/torch/_utils.py", line 705, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 316, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 154, in collate
    clone.update({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 154, in <dictcomp>
    clone.update({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 141, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 222, in collate_numpy_array_fn
    return collate([torch.as_tensor(b) for b in batch], collate_fn_map=collate_fn_map)
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 141, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 213, in collate_tensor_fn
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [3, 1688, 1695] at entry 0 and [3, 1688, 1726] at entry 11`

### Operating System

operating system

Linux

### DeepLabCut version

dlc version

3.0.0.rc2

### DeepLabCut mode

multi animal

### Device type

gpu

### Steps To Reproduce

create shuffle step：
```
from pathlib import Path
import deeplabcut
from deeplabcut.core.engine import Engine
from deeplabcut.core.weight_init import WeightInitialization
from deeplabcut.modelzoo.utils import (
    create_conversion_table,
    read_conversion_table_from_csv,
)
from deeplabcut.utils.pseudo_label import keypoint_matching

def create_training_dataset(config_path, shuffle, super_animal_name, model_name, conversion_table_path, net_type):
    # Step 1: Keypoint matching before creating the training dataset
    keypoint_matching(config_path, super_animal_name, model_name)

    # Step 2: Initialize weights for memory replay
    table = create_conversion_table(
        config=config_path,
        super_animal=super_animal_name,
        project_to_super_animal=read_conversion_table_from_csv(conversion_table_path),
    )
    
    weight_init = WeightInitialization(
        dataset=super_animal_name,
        conversion_array=table.to_array(),
        with_decoder=True,
        memory_replay=True,
    )

    # Step 3: Create training dataset
    deeplabcut.create_training_dataset(
        config_path,
        Shuffles=[shuffle],
        net_type=net_type,
        weight_init=weight_init,
        engine=Engine.PYTORCH,
        userfeedback=False
    )

def main():
    dlc_proj_root = Path("/ssd01/user_acc_data/oppa/deeplabcut/projects/oppamousetracker-Oppa-2024-08-23")
    super_animal_name = "superanimal_topviewmouse"
    net_type = 'top_down_hrnet_w32'
    model_name = 'hrnetw32'
    shuffle = 1

    config_path = str(dlc_proj_root / "config.yaml")
    conversion_table_path = dlc_proj_root / "memory_replay" / "conversion_table.csv"

    # Step 1: Create training dataset
    create_training_dataset(config_path, shuffle, super_animal_name, model_name, conversion_table_path, net_type)

if __name__ == "__main__":
    main()

training step：
`from pathlib import Path
import deeplabcut

def train_network(config_path, shuffle, device, net_type):
    # Train the network with memory replay
    deeplabcut.train_network(
        config_path, 
        shuffle=shuffle, 
        device=device, 
        pose_threshold=0.1, 
        net_type=net_type,
        detector_batch_size=32,
        batch_size=64,
        freeze_bn_stats=False
    )

def main():
    dlc_proj_root = Path("/ssd01/user_acc_data/oppa/deeplabcut/projects/oppamousetracker-Oppa-2024-08-23")
    net_type = 'top_down_hrnet_w32'
    device = "cuda"
    shuffle = 1

    config_path = str(dlc_proj_root / "config.yaml")

    # Step 2: Train the network
    train_network(config_path, shuffle, device, net_type)

if __name__ == "__main__":
    main()
```

error report：
`--------------------------------------------------
Traceback (most recent call last):
  File "/ssd01/user_acc_data/oppa/deeplabcut/code/satvm_training.py", line 29, in <module>
    main()
  File "/ssd01/user_acc_data/oppa/deeplabcut/code/satvm_training.py", line 26, in main
    train_network(config_path, shuffle, device, net_type)
  File "/ssd01/user_acc_data/oppa/deeplabcut/code/satvm_training.py", line 6, in train_network
    deeplabcut.train_network(
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/compat.py", line 245, in train_network
    return train_network(
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/apis/train.py", line 326, in train_network
    train(
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/apis/train.py", line 189, in train
    runner.fit(
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/runners/train.py", line 170, in fit
    train_loss = self._epoch(
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/runners/train.py", line 220, in _epoch
    for i, batch in enumerate(loader):
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/torch/_utils.py", line 705, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 316, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 154, in collate
    clone.update({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 154, in <dictcomp>
    clone.update({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 141, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 222, in collate_numpy_array_fn
    return collate([torch.as_tensor(b) for b in batch], collate_fn_map=collate_fn_map)
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 141, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 213, in collate_tensor_fn
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [3, 1688, 1695] at entry 0 and [3, 1688, 1726] at entry 11`

### Relevant log output

```shell
pytorch_config:

Task:
scorer:
date:
multianimalproject:
identity:
project_path:
engine: tensorflow
video_sets:
bodyparts:
start:
stop:
numframes2pick:
skeleton: []
skeleton_color: black
pcutoff:
dotsize:
alphavalue:
colormap:
TrainingFraction:
iteration:
default_net_type:
default_augmenter:
snapshotindex:
detector_snapshotindex:
batch_size:
cropping:
x1:
x2:
y1:
y2:
corner2move2:
move2corner:
SuperAnimalConversionTables:
data:
  colormode: RGB
  inference:
    auto_padding:
      pad_width_divisor: 32
      pad_height_divisor: 32
    normalize_images: true
  train:
    affine:
      p: 0.5
      scaling:
      - 1.0
      - 1.0
      rotation: 30
      translation: 0
    gaussian_noise: 12.75
    normalize_images: true
    auto_padding:
      pad_width_divisor: 32
      pad_height_divisor: 32
detector:
  data:
    colormode: RGB
    inference:
      normalize_images: true
    train:
      hflip: true
      normalize_images: true
  device: auto
  model:
    type: FasterRCNN
    variant: fasterrcnn_resnet50_fpn_v2
    box_score_thresh: 0.6
    pretrained: false
  runner:
    type: DetectorTrainingRunner
    eval_interval: 50
    optimizer:
      type: AdamW
      params:
        lr: 1e-05
    scheduler:
      type: LRListScheduler
      params:
        milestones:
        - 90
        lr_list:
        - - 1e-06
    snapshots:
      max_snapshots: 5
      save_epochs: 50
      save_optimizer_state: false
  train_settings:
    batch_size: 32
    dataloader_workers: 32
    dataloader_pin_memory: true
    display_iters: 500
    epochs: 250
device: auto
metadata:
  project_path: /ssd01/user_acc_data/oppa/deeplabcut/projects/oppamousetracker-Oppa-2024-08-23
  pose_config_path: 
    /ssd01/user_acc_data/oppa/deeplabcut/projects/oppamousetracker-Oppa-2024-08-23/dlc-models-pytorch/iteration-0/oppamousetrackerAug23-trainset90shuffle1/train/pose_cfg.yaml
  bodyparts:
  - nose
  - left_ear
  - right_ear
  - left_ear_tip
  - right_ear_tip
  - left_eye
  - right_eye
  - neck
  - mid_back
  - mouse_center
  - mid_backend
  - mid_backend2
  - mid_backend3
  - tail_base
  - tail1
  - tail2
  - tail3
  - tail4
  - tail5
  - left_shoulder
  - left_midside
  - left_hip
  - right_shoulder
  - right_midside
  - right_hip
  - tail_end
  - head_midpoint
  unique_bodyparts: []
  individuals:
  - individual1
  - individual2
  - individual3
  - individual4
  - individual5
  - individual6
  - individual7
  - individual8
  - individual9
  - individual10
  with_identity: false
method: td
model:
  backbone:
    type: HRNet
    model_name: hrnet_w32
    pretrained: false
    freeze_bn_stats: false
    freeze_bn_weights: false
    interpolate_branches: false
    increased_channel_count: false
  backbone_output_channels: 32
  heads:
    bodypart:
      type: HeatmapHead
      weight_init: normal
      predictor:
        type: HeatmapPredictor
        apply_sigmoid: false
        clip_scores: true
        location_refinement: false
        locref_std: 7.2801
      target_generator:
        type: HeatmapGaussianGenerator
        num_heatmaps: 27
        pos_dist_thresh: 17
        heatmap_mode: KEYPOINT
        generate_locref: false
        locref_std: 7.2801
      criterion:
        heatmap:
          type: WeightedMSECriterion
          weight: 1.0
      heatmap_config:
        channels:
        - 32
        - 27
        kernel_size:
        - 1
        strides:
        - 1
net_type: top_down_hrnet_w32
runner:
  type: PoseTrainingRunner
  key_metric: test.mAP
  key_metric_asc: true
  eval_interval: 10
  optimizer:
    type: AdamW
    params:
      lr: 1e-05
  scheduler:
    type: LRListScheduler
    params:
      lr_list:
      - - 1e-06
      - - 1e-07
      milestones:
      - 160
      - 190
  snapshots:
    max_snapshots: 5
    save_epochs: 25
    save_optimizer_state: false
train_settings:
  batch_size: 64
  dataloader_workers: 64
  dataloader_pin_memory: true
  display_iters: 500
  epochs: 200
  pretrained_weights:
  seed: 42
  weight_init:
    dataset: superanimal_topviewmouse
    with_decoder: true
    memory_replay: true
    conversion_array:
    - 0
    - 1
    - 2
    - 7
    - 9
    - 13
freeze_bn_stats: false
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @Chap5732! I believe the issue comes from the fact that your dataset contains images that have different sizes (`[3, 1688, 1695]` at entry 0 and `[3, 1688, 1726]` at entry 1, so one image is `1695x1688` and another is `1726x1688`), but there is no appropriate "collate" function to resize all of them to the same dimensions defined in your `pytorch_config.yaml`.

Having images of different sizes in a dataset is not at all a problem: you can either train with batch size 1, resize them all to the same size, or resize them when they are grouped into a batch so that all images in a batch have the same size. This last option is what I would do (and it's better explained how to do that exactly [in the docs](https://deeplabcut.github.io/DeepLabCut/docs/pytorch/pytorch_config.html#data)).

These SuperAnimal models are top-down (with an object detector to localize individuals, and a pose model to estimate pose). You only need to apply this collate configuration for the object detector, as the pose model will always receive images that are 256x256 pixels. You can set configure the collate function in your `pytorch_config.yaml` as follows: 

```yaml
detector:
  data:
    colormode: RGB
    inference:
      normalize_images: true
    train:
      hflip: true
      normalize_images: true
      collate:
        type: ResizeFromDataSizeCollate
        min_scale: 0.4
        max_scale: 1.0
        min_short_side: 128
        max_short_side: 1152
        multiple_of: 32
        to_square: false
```

I've noticed this collate configuration isn't added as a default for SuperAnimal models, so I'll update the code so that's the case.

Let me know if this fixes your bug or if you have other questions!

**Comment by Chap5732** [comment]
Thank you @n-poulsen ! After adding the collate function to my pytorch config file I successfully trained the model on my dataset! 

But I encounter another error when I tried to evaluate the model :


```
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
Evaluating network...
100%|██████████████████████████████████████████████████████████████████████████| 338/338 [00:33<00:00, 10.19it/s]
100%|██████████████████████████████████████████████████████████████████████████| 338/338 [01:03<00:00,  5.35it/s]
Traceback (most recent call last):
  File "/ssd01/user_acc_data/oppa/deeplabcut/code/evaluation.py", line 16, in <module>
    evaluate_network(project_name, shuffle)
  File "/ssd01/user_acc_data/oppa/deeplabcut/code/evaluation.py", line 9, in evaluate_network
    deeplabcut.evaluate_network(config_path,
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/compat.py", line 476, in evaluate_network
    return evaluate_network(
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/apis/evaluate.py", line 445, in evaluate_network
    evaluate_snapshot(
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/apis/evaluate.py", line 239, in evaluate_snapshot
    results, predictions_for_split = evaluate(
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/apis/evaluate.py", line 127, in evaluate
    pred["bodyparts"] = pred["bodyparts"][:, conversion_array]
IndexError: index 7 is out of bounds for axis 1 with size 6
```

And when I tried to skip the evaluation and perform the analyze_video step of the model on my test videos I encounter such error:

```
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
Analyzing all videos in folder: /ssd01/user_acc_data/oppa/deeplabcut/projects/oppamousetracker-Oppa-2024-08-23/analyze_videos/shuffle1/Approach/cropped with shuffle: 1
Analyzing videos with /ssd01/user_acc_data/oppa/deeplabcut/projects/oppamousetracker-Oppa-2024-08-23/dlc-models-pytorch/iteration-0/oppamousetrackerAug23-trainset90shuffle1/train/snapshot-200.pt
  -> Using detector /ssd01/user_acc_data/oppa/deeplabcut/projects/oppamousetracker-Oppa-2024-08-23/dlc-models-pytorch/iteration-0/oppamousetrackerAug23-trainset90shuffle1/train/snapshot-detector-250.pt
Starting to analyze /ssd01/user_acc_data/oppa/deeplabcut/projects/oppamousetracker-Oppa-2024-08-23/analyze_videos/shuffle1/Approach/cropped/DEMO1cropped.mp4
Video metadata: 
  Overall # of frames:    138
  Duration of video [s]:  4.60
  fps:                    30.0
  resolution:             w=1742, h=1672

Running Detector
100%|██████████████████████████████████████████████████████████████████████████| 138/138 [00:08<00:00, 15.34it/s]
Running Pose Prediction
100%|██████████████████████████████████████████████████████████████████████████| 138/138 [00:51<00:00,  2.69it/s]
Saving results in /ssd01/user_acc_data/oppa/deeplabcut/projects/oppamousetracker-Oppa-2024-08-23/analyze_videos/shuffle1/Approach/cropped/DEMO1croppedDLC_TopDownHrnetW32_oppamousetrackerAug23shuffle1_detector_250_snapshot_200.h5 and /ssd01/user_acc_data/oppa/deeplabcut/projects/oppamousetracker-Oppa-2024-08-23/analyze_videos/shuffle1/Approach/cropped/DEMO1croppedDLC_TopDownHrnetW32_oppamousetrackerAug23shuffle1_detector_250_snapshot_200_full.pickle
Traceback (most recent call last):
  File "/ssd01/user_acc_data/oppa/deeplabcut/code/analyze_videos.py", line 39, in <module>
    main()
  File "/ssd01/user_acc_data/oppa/deeplabcut/code/analyze_videos.py", line 36, in main
    analyze_videos_in_folder_or_file(config_path, input_path, shuffle)
  File "/ssd01/user_acc_data/oppa/deeplabcut/code/analyze_videos.py", line 23, in analyze_videos_in_folder_or_file
    deeplabcut.analyze_videos(config_path, video_files, save_as_csv=True, batchsize=64, shuffle=shuffle)
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/compat.py", line 856, in analyze_videos
    return analyze_videos(
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/apis/analyze_videos.py", line 345, in analyze_videos
    df = create_df_from_prediction(
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/apis/analyze_videos.py", line 432, in create_df_from_prediction
    df = pd.DataFrame(
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/pandas/core/frame.py", line 827, in __init__
    mgr = ndarray_to_mgr(
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 336, in ndarray_to_mgr
    _check_values_indices_shape_match(values, index, columns)
  File "/share/user_data/oppa/.conda/envs/dlc-oppa/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 420, in _check_values_indices_shape_match
    raise ValueError(f"Shape of passed values is {passed}, indices imply {implied}")
ValueError: Shape of passed values is (138, 810), indices imply (138, 180)
```


I noticed that the number of my labels, which is 6, can be multipled by 30 and get 180 and 810 can be got with 27 multiplying 30, which is the number of sa-tvm's labels. Does the error have something to do with the superanimal model config?

Here is my pytorch_config file:
```
Task:
scorer:
date:
multianimalproject:
identity:
project_path: 
  /ssd01/user_acc_data/oppa/deeplabcut/projects/oppamousetracker-Oppa-2024-08-23/dlc-models-pytorch/iteration-0/oppamousetrackerAug23-trainset90shuffle1/train
engine: tensorflow
video_sets:
bodyparts:
start:
stop:
numframes2pick:
skeleton: []
skeleton_color: black
pcutoff:
dotsize:
alphavalue:
colormap:
TrainingFraction:
iteration:
default_net_type:
default_augmenter:
snapshotindex:
detector_snapshotindex:
batch_size:
cropping:
x1:
x2:
y1:
y2:
corner2move2:
move2corner:
SuperAnimalConversionTables:
data:
  colormode: RGB
  inference:
    auto_padding:
      pad_width_divisor: 32
      pad_height_divisor: 32
    normalize_images: true
  train:
    affine:
      p: 0.5
      scaling:
      - 1.0
      - 1.0
      rotation: 30
      translation: 0
    gaussian_noise: 12.75
    normalize_images: true
    auto_padding:
      pad_width_divisor: 32
      pad_height_divisor: 32
detector:
  data:
    colormode: RGB
    inference:
      normalize_images: true
    train:
      hflip: true
      normalize_images: true
      collate:
        type: ResizeFromDataSizeCollate
        min_scale: 0.4
        max_scale: 1.0
        min_short_side: 128
        max_short_side: 1152
        multiple_of: 32
        to_square: false
  device: auto
  model:
    type: FasterRCNN
    variant: fasterrcnn_resnet50_fpn_v2
    box_score_thresh: 0.6
    pretrained: false
  runner:
    type: DetectorTrainingRunner
    eval_interval: 50
    optimizer:
      type: AdamW
      params:
        lr: 1e-05
    scheduler:
      type: LRListScheduler
      params:
        milestones:
        - 90
        lr_list:
        - - 1e-06
    snapshots:
      max_snapshots: 5
      save_epochs: 50
      save_optimizer_state: false
  train_settings:
    batch_size: 32
    dataloader_workers: 32
    dataloader_pin_memory: true
    display_iters: 500
    epochs: 250
device: auto
metadata:
  project_path: /ssd01/user_acc_data/oppa/deeplabcut/projects/oppamousetracker-Oppa-2024-08-23
  pose_config_path: 
    /ssd01/user_acc_data/oppa/deeplabcut/projects/oppamousetracker-Oppa-2024-08-23/dlc-models-pytorch/iteration-0/oppamousetrackerAug23-trainset90shuffle1/train/pose_cfg.yaml
  bodyparts:
  - nose
  - left_ear
  - right_ear
  - left_ear_tip
  - right_ear_tip
  - left_eye
  - right_eye
  - neck
  - mid_back
  - mouse_center
  - mid_backend
  - mid_backend2
  - mid_backend3
  - tail_base
  - tail1
  - tail2
  - tail3
  - tail4
  - tail5
  - left_shoulder
  - left_midside
  - left_hip
  - right_shoulder
  - right_midside
  - right_hip
  - tail_end
  - head_midpoint
  unique_bodyparts: []
  individuals:
  - individual1
  - individual2
  - individual3
  - individual4
  - individual5
  - individual6
  - individual7
  - individual8
  - individual9
  - individual10
  with_identity: false
method: td
model:
  backbone:
    type: HRNet
    model_name: hrnet_w32
    pretrained: false
    freeze_bn_stats: false
    freeze_bn_weights: false
    interpolate_branches: false
    increased_channel_count: false
  backbone_output_channels: 32
  heads:
    bodypart:
      type: HeatmapHead
      weight_init: normal
      predictor:
        type: HeatmapPredictor
        apply_sigmoid: false
        clip_scores: true
        location_refinement: false
        locref_std: 7.2801
      target_generator:
        type: HeatmapGaussianGenerator
        num_heatmaps: 27
        pos_dist_thresh: 17
        heatmap_mode: KEYPOINT
        generate_locref: false
        locref_std: 7.2801
      criterion:
        heatmap:
          type: WeightedMSECriterion
          weight: 1.0
      heatmap_config:
        channels:
        - 32
        - 27
        kernel_size:
        - 1
        strides:
        - 1
net_type: top_down_hrnet_w32
runner:
  type: PoseTrainingRunner
  key_metric: test.mAP
  key_metric_asc: true
  eval_interval: 10
  optimizer:
    type: AdamW
    params:
      lr: 1e-05
  scheduler:
    type: LRListScheduler
    params:
      lr_list:
      - - 1e-06
      - - 1e-07
      milestones:
      - 160
      - 190
  snapshots:
    max_snapshots: 5
    save_epochs: 25
    save_optimizer_state: false
train_settings:
  batch_size: 64
  dataloader_workers: 32
  dataloader_pin_memory: true
  display_iters: 500
  epochs: 200
  pretrained_weights:
  seed: 42
  weight_init:
    dataset: superanimal_topviewmouse
    with_decoder: true
    memory_replay: true
    conversion_array:
    - 0
    - 1
    - 2
    - 7
    - 9
    - 13
freeze_bn_stats: false
```
