### ISSUE TITLE
Analyse videos function giving out of memory errors DLC3.0.0rc8

### ISSUE THREAD

**Issue by stef1029** [DeepLabCut/DeepLabCut#2983]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Operating System

Alma Linux

### DeepLabCut version

3.0.0rc6 and rc8

### What engine are you using?

pytorch

### DeepLabCut mode

single animal

### Device type

GeForce RTX 2080 Ti - 11GB and RTX 4090 - 24GB (cluster)

### Bug description 🐛

Hi,
I'm aware there are a couple of open issues that look similar to this bug but they have got slightly different issues I believe. I am running single mouse tracking on our cluster and am getting much slower than normal inference times (0.5x roughly, c. 10it/s) and out of memory errors on videos that are only 19gb in size (c. 1.5hrs long) even when using 250G memory for the job. I'm not sure what parts of my code and setup are relevant for solving this so I thought I'd just put this here and see.
Thanks for any help you can give,
Stefan

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by HLH2000** [comment]
Did you try reducing the batch size in your config file?

**Comment by stef1029** [comment]
hi @HLH2000 , my batch size is 8. I'll paste in my scripts for some more context.

Config file:
```
# Project definitions (do not edit)
Task: LMDC
scorer: StefanRC
date: Mar11
multianimalproject: false
identity:


# Project path (change when moving around)
project_path: 
  /cephfs2/srogers/2503_DLC_model_videos/LMDC_model_videos/LMDC-StefanRC-2025-03-11


# Default DeepLabCut engine to use for shuffle creation (either pytorch or tensorflow)
engine: pytorch


# Annotation data set configuration (and individual video cropping parameters)
video_sets:
  /cephfs2/srogers/2503_DLC_model_videos/LMDC_model_videos/250205_205702_output.avi:
    crop: 0, 1280, 0, 1024
  /cephfs2/srogers/2503_DLC_model_videos/LMDC_model_videos/250205_205243_output.avi:
    crop: 0, 1280, 0, 1024
  /cephfs2/srogers/2503_DLC_model_videos/LMDC_model_videos/250205_204531_output.avi:
    crop: 0, 1280, 0, 1024
  /cephfs2/srogers/2503_DLC_model_videos/LMDC_model_videos/250205_204934_output.avi:
    crop: 0, 1280, 0, 1024
  /cephfs2/srogers/2503_DLC_model_videos/LMDC_model_videos/250205_210318_output.avi:
    crop: 0, 1280, 0, 1024
  /cephfs2/srogers/2503_DLC_model_videos/LMDC_model_videos/250205_210030_output.avi:
    crop: 0, 1280, 0, 1024
bodyparts:
- nose
- head
- left_ear
- right_ear
- spine_1
- spine_2
- spine_3
- spine_4


# Fraction of video to start/stop when extracting frames for labeling/refinement


# Fraction of video to start/stop when extracting frames for labeling/refinement


# Fraction of video to start/stop when extracting frames for labeling/refinement
start: 0
stop: 1
numframes2pick: 20


# Plotting configuration
skeleton:
- - nose
  - head
- - head
  - left_ear
- - head
  - right_ear
- - head
  - spine_1
- - spine_1
  - spine_2
- - spine_2
  - spine_3
- - spine_3
  - spine_4
skeleton_color: black
pcutoff: 0.6
dotsize: 12
alphavalue: 0.7
colormap: rainbow


# Training,Evaluation and Analysis configuration
TrainingFraction:
- 0.95
iteration: 0
default_net_type: resnet_50
default_augmenter: default
snapshotindex: -1
detector_snapshotindex: -1
batch_size: 8


# Cropping Parameters (for analysis and outlier frame detection)
cropping: false
#if cropping is true for analysis, then set the values here:
x1: 0
x2: 640
y1: 277
y2: 624


# Refinement configuration (parameters from annotation dataset configuration also relevant in this stage)
corner2move2:
- 50
- 50
move2corner: true


# Conversion tables to fine-tune SuperAnimal weights
SuperAnimalConversionTables:
detector_batch_size: 1
```
Submitting script:
```
#!/bin/bash -l

#SBATCH --gres=gpu:1
#SBATCH --partition=gpu
#SBATCH --mem=250G
#SBATCH --mail-type=BEGIN,END,FAIL

# Calculate the GPU ID to use by this task
NUM_GPUS=1
GPU_ID=$((SLURM_ARRAY_TASK_ID % NUM_GPUS))

# Define the index of the video this particular job should process
VIDEO_INDEX=$SLURM_ARRAY_TASK_ID

# Path to your list of videos
VIDEO_LIST="videos_to_analyse.txt"

# Extract the specific video path for this job
VIDEO_PATH=$(sed -n "${VIDEO_INDEX}p" $VIDEO_LIST)

# Extract just the filename without extension from the path for use in output naming
VIDEO_BASENAME=$(basename "$VIDEO_PATH" | sed 's/\.[^.]*$//')

echo "Processing video: $VIDEO_PATH on GPU: $GPU_ID"

# Get the current directory where the script is running from
CURRENT_DIR=$(pwd)

# Create a temporary log file
TEMP_LOG="${CURRENT_DIR}/${VIDEO_BASENAME}_temp.log"

# Redirect all output to the temporary log file
exec > "$TEMP_LOG" 2>&1

echo "Starting job at $(date)"
echo "Video: $VIDEO_PATH"
echo "GPU ID: $GPU_ID"

conda activate DEEPLABCUT3

# cd "/cephfs2/srogers/New_analysis_pipeline/Scripts"
cd "/lmb/home/srogers/Dev/projects/hex_behav_analysis/hex_behav_analysis/dlc_scripts"

# Run the Python script and capture its exit code
echo "Running batch_analyse.py..."
python batch_analyse.py "$VIDEO_PATH" "$GPU_ID"
PYTHON_EXIT_CODE=$?

# Check if the Python script failed and rename the log file accordingly
if [ $PYTHON_EXIT_CODE -ne 0 ]; then
    echo "ERROR: Python script failed with exit code $PYTHON_EXIT_CODE"
    echo "Job failed at $(date)"
    
    # Rename the temporary log file to include FAILED in the name
    FINAL_LOG="${CURRENT_DIR}/${VIDEO_BASENAME}_FAILED.log"
else
    echo "Python script completed successfully"
    echo "Job completed at $(date)"
    
    # Rename the temporary log file to include SUCCESS in the name
    FINAL_LOG="${CURRENT_DIR}/${VIDEO_BASENAME}_SUCCESS.log"
fi

# Close the file descriptors before moving the file
exec >&- 2>&-

# Move the temporary log to the final log with the appropriate status in the filename
mv "$TEMP_LOG" "$FINAL_LOG"

# Exit with the Python script's exit code
exit $PYTHON_EXIT_CODE
```
Analysis script:
```
from deeplabcut import analyze_videos
import time
import sys



# config = r'/cephfs2/srogers/New_analysis_pipeline/training_videos/DLC_Project_231212_193535_wtjx285-2a_raw_MP-SRC-2024-01-09/config.yaml'
# config = r'/cephfs2/dwelch/6-choice_behaviour_DLC_model/config.yaml'
config = r'/cephfs2/srogers/2503_DLC_model_videos/LMDC_model_videos/LMDC-StefanRC-2025-03-11/config.yaml'

def analyse(video_path, gpu_id):
    start_time = time.perf_counter()
    print(f"Analyzing {str(video_path)}")
    print(f"Using GPU {gpu_id}")
    analyze_videos(config = config,
                          videos = [video_path], 
                          videotype='.avi', 
                          save_as_csv=True, 
                          gputouse=gpu_id)
    # give time in minutes and seconds, rounded:
    print(f"""Analysis of {str(video_path)} complete. 
                \rTook: {round((time.perf_counter() - start_time)/60, 2)} minutes 
                \rand {round((time.perf_counter() - start_time)%60, 2)} seconds""")
    

if __name__ == "__main__":
    video_path = sys.argv[1]
    gpu_id = int(sys.argv[2])

    analyse(video_path, gpu_id)

```
