### ISSUE TITLE
Evaluation Results not reported (empty files created and no plotting)

### ISSUE THREAD

**Issue by ghost** [DeepLabCut/DeepLabCut#352]
**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.

 Anaconda Env. for GUI stuff

Please complete the following information about your system:

OS: iOS 10.13.6.
DeepLabCut Version: DeepLabCut 2.0.7.1.
Browser: Google Chrome (Google Collab)

**Describe the problem**

I've trained a network to 230,000 iterations on Google Collab. And when I run the evaluate_network, two things happen. The first time around, it appears to start to evaluate and eventually, among other things,  throws an error about the .h5 file not being found (see below). When this happens, I re launch my google drive and see the evaluations-results>iteration0>headOrientation-moving_arudinoJun27-trainset95shuffle1>DeepCut_resnet50_headOrientation-mo…ing_arudinoJun27shuffle1_230000-snapshot-230000.h5 (215kb).  

If I run the cell again, without changing anything, I then get no error, and a report that everything went well (the evaluations folder has already been created, the shuffle folder already exists, And that the net has already been evaluated ,etc (see below). Here there is no report though of the network evaluation, and then the csv file (as well I assume as the .h5 file) have no reports. They are empty. There's also no folder for plotting.

**How to Reproduce the problem**
1.
 install deeplabcut 2.0 (with all the Collab specific workarounds, suppress GUI, etc)
2. 
from pathlib import Path
path_config_file='/content/drive/Shared drives/DeepLabCut2.0/DLC_Project/headOrientation-moving_arudino-JG-2019-06-27
3. (training dataset was created, and the network was trained to iteration-232,000 ) 
4.
%matplotlib notebook
deeplabcut.evaluate_network(path_config_file,plotting=True)

**Screenshots**
**Run deeplabcut.evaluate_network(path_config_file,plotting=True) first time around:**

```
Running  DeepCut_resnet50_headOrientation-moving_arudinoJun27shuffle1_230000  with # of trainingiterations: 230000
0it [00:00, ?it/s]Analyzing data...
220it [00:09, 22.63it/s]
Done and results stored for snapshot:  snapshot-230000
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
/usr/lib/python3.6/contextlib.py in __exit__(self, type, value, traceback)
     98             try:
---> 99                 self.gen.throw(type, value, traceback)
    100             except StopIteration as exc:

5 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in get_controller(self, default)
   5651                  self).get_controller(default) as g, context.graph_mode():
-> 5652         yield g
   5653     finally:

/usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/evaluate.py in evaluate_network(config, Shuffles, plotting, show_errors, comparisonbodyparts, gputouse)
    154                 try:
--> 155                     DataMachine = pd.read_hdf(resultsfilename,'df_with_missing')
    156                     print("This net has already been evaluated!")

/usr/local/lib/python3.6/dist-packages/pandas/io/pytables.py in read_hdf(path_or_buf, key, mode, **kwargs)
    370             raise compat.FileNotFoundError(
--> 371                 'File %s does not exist' % path_or_buf)
    372 

FileNotFoundError: File /content/drive/Shared drives/DeepLabCut2.0/DLC_Projects/headOrientation-moving_arudino-JG-2019-06-27/evaluation-results/iteration-0/headOrientation-moving_arudinoJun27-trainset95shuffle1/DeepCut_resnet50_headOrientation-moving_arudinoJun27shuffle1_230000-snapshot-230000.h5 does not exist

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-20-d8366108eec8> in <module>()
      1 get_ipython().magic('matplotlib notebook')
----> 2 deeplabcut.evaluate_network(path_config_file,plotting=True)
      3 
      4 # Here you want to see a low pixel error! Of course, it can only be as good as the labeler, so be sure your labels are good!

/usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/evaluate.py in evaluate_network(config, Shuffles, plotting, show_errors, comparisonbodyparts, gputouse)
    187                     print("Done and results stored for snapshot: ", Snapshots[snapindex])
    188                     DataCombined = pd.concat([Data.T, DataMachine.T], axis=0).T
--> 189                     RMSE,RMSEpcutoff = pairwisedistances(DataCombined, cfg["scorer"], DLCscorer,cfg["pcutoff"],comparisonbodyparts)
    190                     testerror = np.nanmean(RMSE.iloc[testIndices].values.flatten())
    191                     trainerror = np.nanmean(RMSE.iloc[trainIndices].values.flatten())

/usr/local/lib/python3.6/dist-packages/ruamel/yaml/comments.py in __getitem__(self, key)
    689         # type: (Any) -> Any
    690         try:
--> 691             return ordereddict.__getitem__(self, key)
    692         except KeyError:
    693             for merged in getattr(self, merge_attrib, []):

KeyError: 'pcutoff'`
```

**When I run this cell again without changing anything (deeplabcut.evaluate_network(path_config_file,plotting=True).**

```

Config:
{'all_joints': [[0],
                [1],
                [2],
                [3],
                [4],
                [5],
                [6],
                [7],
                [8],
                [9],
                [10],
                [11],
                [12],
                [13],
                [14],
                [15],
                [16],
                [17],
                [18],
                [19],
                [20],
                [21],
                [22],
                [23],
                [24],
                [25],
                [26],
                [27]],
 'all_joints_names': ['FiberTipLower',
                      'FiberTipUpper',
                      'fiberBase_R',
                      'fiberBase_L',
                      'fiberBase_C',
                      'earU_R',
                      'earL_R',
                      'earU_L',
                      'earL_L',
                      'eyeU_L',
                      'eyeL_L',
                      'eyeU_R',
                      'eyeL_R',
                      'snout_R',
                      'snout_L',
                      'snout_C',
                      'frontPaw_right',
                      'frontPaw_left',
                      'backPaw_right',
                      'backPaw_left',
                      'light_On',
                      'Top_R',
                      'Top_L',
                      'Bottom_R',
                      'Bottom_L',
                      'Tail_U',
                      'Tail_M',
                      'Tail_L'],
 'batch_size': 1,
 'bottomheight': 400,
 'crop': True,
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets/iteration-0/UnaugmentedDataSet_headOrientation-moving_arudinoJun27/headOrientation-moving_arudino_JG95shuffle1.mat',
 'dataset_type': 'default',
 'deterministic': False,
 'display_iters': 1000,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': '/usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'leftwidth': 400,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'max_input_size': 1500,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets/iteration-0/UnaugmentedDataSet_headOrientation-moving_arudinoJun27/Documentation_data-headOrientation-moving_arudino_95shuffle1.pickle',
 'min_input_size': 64,
 'minsize': 100,
 'mirror': False,
 'multi_step': [[0.005, 10000],
                [0.02, 430000],
                [0.002, 730000],
                [0.001, 1030000]],
 'net_type': 'resnet_50',
 'num_joints': 28,
 'optimizer': 'sgd',
 'pos_dist_thresh': 17,
 'project_path': '/content/drive/Shared '
                 'drives/DeepLabCut2.0/DLC_Projects/headOrientation-moving_arudino-JG-2019-06-27',
 'regularize': False,
 'rightwidth': 400,
 'save_iters': 5000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': '/content/drive/Shared '
                    'drives/DeepLabCut2.0/DLC_Projects/headOrientation-moving_arudino-JG-2019-06-27/dlc-models/iteration-0/headOrientation-moving_arudinoJun27-trainset95shuffle1/test/snapshot',
 'stride': 8.0,
 'topheight': 400,
 'use_gt_segm': False,
 'video': False,
 'video_batch': False,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
/content/drive/Shared drives/DeepLabCut2.0/DLC_Projects/Orientation-moving_arudino-JG-2019-06-27/evaluation-results/  already exists!
/content/drive/Shared drives/DeepLabCut2.0/DLC_Projects/Orientation-moving_arudino-JG-2019-06-27/evaluation-results/iteration-0/headOrientation-moving_arudinoJun27-trainset95shuffle1  already exists!
Running  DeepCut_resnet50_headOrientation-moving_arudinoJun27shuffle1_230000  with # of trainingiterations: 230000
This net has already been evaluated!
The network is evaluated and the results are stored in the subdirectory 'evaluation_results'.
If it generalizes well, choose the best model for prediction and update the config file with the appropriate index for the 'snapshotindex'.
Use the function 'analyze_video' to make predictions on new videos.
Otherwise consider retraining the network (see DeepLabCut workflow Fig 2)
/content/drive/Shared drives/headOrientation-moving_arudino-JG-2019-06-27/evaluation-results/  already exists!
/content/drive/Shared drives/headOrientation-moving_arudino-JG-2019-06-27/evaluation-results/iteration-0/headOrientation-moving_arudinoJun27-trainset95shuffle1  already exists!
Running  DeepCut_resnet50_headOrientation-moving_arudinoJun27shuffle1_230000  with # of trainingiterations: 230000
This net has already been evaluated!
The network is evaluated and the results are stored in the subdirectory 'evaluation_results'.
If it generalizes well, choose the best model for prediction and update the config file with the appropriate index for the 'snapshotindex'.
Use the function 'analyze_video' to make predictions on new videos.
Otherwise consider retraining the network (see DeepLabCut workflow Fig 2)

```
**Additional context**

At some point when I was training the network it stopped, and I went back to continue training it on iteration 205,000. So when it restarted training, it re-started the iteration number back to 0 (even though it was trained on the 205,000 shuffle). So the new iteration number of 230,000 is from the second time around. I don't know if this would affect it at all?

**Comment by MMathisLab** [comment]
seems it crashed somehow; perhaps google colab disconnected or such. delete the folder evaluation-results and try again...

The re-training point should not matter.

**Comment by ghost** [comment]
I've done this several times (8+) with restarting the browser and I keep running into the same problem. 

(1) At first i thought it might be related to having the space in the config_path because it's on a Google Shared drive, so it formats oddly in the config file, but if I trained using that path, and it's still creating the files it's suppose to in the right destinations.

(2) All the files in the training-dataset are there .csv (202 KB), .h5 (119KB), .pickle 148 (KB), .mat (175 KB). And from what I see from the CSV file, all the labeled data is there.

(3) I could delete all other snapshots in the dlc-models>>test folder, but I don't think that is the case. And the snapshot-23000.data-00000-of-00001 (96MB), snapshot-230000.index (11KB), snapshot-230000(2MB) -- which I believe suggests that all the training was stored correctly.

(3a) The empty files that are produced **the second time in the evaluation** results are: 
a) DeepCut_resnet50_FheadOrientation-moving_arudinoJun27shuffle1_230000-results.csv (153 bytes)
b) DeepCut_resnet50_headOrientation-moving_arudinoJun27shuffle1_230000-results.h5 (1KB), 
3) DeepCut_resnet50_headOrientation-moving_arudinoJun27shuffle1_230000-snapshot-230000.h5 (215KB)

And it's here (as well as when it reports that it has been evaluated but no reports are given) that I can see that the .csv file is empty. 

(4) One thing I don't think would affect it is that my videos folder right now doesn't have links to the videos (since I migrated everything to Google Collab after initializing and labeling on GUI. So the shortcuts to the video files didn't migrate correctly (maybe because it was also on Google Drive > Shared? But I don't think that's relevant to evaluation process.

**Comment by MMathisLab** [comment]
Are you using the latest COLAB notebook, i.e. updated a few days ago?
After you install deeplabcut and then the other funny dependencies that one needs to over-write you have to click "restart runtime":
![Screen Shot 2019-07-08 at 8 52 31 AM](https://user-images.githubusercontent.com/28102185/60811653-c3c4dd00-a15d-11e9-8372-594f8485bac9.png)
![Screen Shot 2019-07-08 at 8 59 59 AM](https://user-images.githubusercontent.com/28102185/60812136-cecc3d00-a15e-11e9-8b53-cc3992470096.png)


(1) it should be fine; I can run the demo right now that is on colab. 
(2) good; You trained on colab, I assume? so under dlc-models those were generated just fine on colab...
(3) isn't required 
(4) should be fine ...

**Comment by ghost** [comment]
Yeah, I've been using the most updated Google Collab and restarting the runtime, etc. But just re-ran opened everything again, and re-ran. I'm still getting, for the most part the same errors. With the same results (first time around exception is listed below) and the second run (w/out changing anything) results in empty files being created. 

Run 1: 
```
W0708 14:43:04.029768 140182862894976 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/nnet/predict.py:22: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

Running  DeepCut_resnet50_FP-RR_grooming-headOrientation-moving_arudinoJun27shuffle1_230000  with # of trainingiterations: 230000
W0708 14:43:06.657097 140182862894976 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/nnet/pose_net.py:74: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

W0708 14:43:07.220063 140182862894976 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/nnet/predict.py:28: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

W0708 14:43:07.437446 140182862894976 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/nnet/predict.py:29: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

W0708 14:43:07.635821 140182862894976 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/nnet/predict.py:30: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.

W0708 14:43:08.647218 140182862894976 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
0it [00:00, ?it/s]Analyzing data...
220it [00:11, 24.77it/s]
Done and results stored for snapshot:  snapshot-230000
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
/usr/lib/python3.6/contextlib.py in __exit__(self, type, value, traceback)
     98             try:
---> 99                 self.gen.throw(type, value, traceback)
    100             except StopIteration as exc:

5 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in get_controller(self, default)
   5651                  self).get_controller(default) as g, context.graph_mode():
-> 5652         yield g
   5653     finally:

/usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/evaluate.py in evaluate_network(config, Shuffles, plotting, show_errors, comparisonbodyparts, gputouse)
    154                 try:
--> 155                     DataMachine = pd.read_hdf(resultsfilename,'df_with_missing')
    156                     print("This net has already been evaluated!")

/usr/local/lib/python3.6/dist-packages/pandas/io/pytables.py in read_hdf(path_or_buf, key, mode, **kwargs)
    346             raise compat.FileNotFoundError(
--> 347                 'File %s does not exist' % path_or_buf)
    348 

FileNotFoundError: File /content/drive/Shared drives/DeepLabCut2.0/DLC_Projects/headOrientation-moving_arudino-JG-2019-06-27/evaluation-results/iteration-0/headOrientation-moving_arudinoJun27-trainset95shuffle1/DeepCut_resnet50_headOrientation-moving_arudinoJun27shuffle1_230000-snapshot-230000.h5 does not exist

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-7-d8366108eec8> in <module>()
      1 get_ipython().magic('matplotlib notebook')
----> 2 deeplabcut.evaluate_network(path_config_file,plotting=True)
      3 
      4 # Here you want to see a low pixel error! Of course, it can only be as good as the labeler, so be sure your labels are good!

/usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/evaluate.py in evaluate_network(config, Shuffles, plotting, show_errors, comparisonbodyparts, gputouse)
    187                     print("Done and results stored for snapshot: ", Snapshots[snapindex])
    188                     DataCombined = pd.concat([Data.T, DataMachine.T], axis=0).T
--> 189                     RMSE,RMSEpcutoff = pairwisedistances(DataCombined, cfg["scorer"], DLCscorer,cfg["pcutoff"],comparisonbodyparts)
    190                     testerror = np.nanmean(RMSE.iloc[testIndices].values.flatten())
    191                     trainerror = np.nanmean(RMSE.iloc[trainIndices].values.flatten())

/usr/local/lib/python3.6/dist-packages/ruamel/yaml/comments.py in __getitem__(self, key)
    689         # type: (Any) -> Any
    690         try:
--> 691             return ordereddict.__getitem__(self, key)
    692         except KeyError:
    693             for merged in getattr(self, merge_attrib, []):

KeyError: 'pcutoff'
```

Run 2: 
```
/content/drive/Shared drives/DeepLabCut2.0/DLC_Projects/headOrientation-moving_arudino-JG-2019-06-27/evaluation-results/  already exists!
/content/drive/Shared drives/DeepLabCut2.0/DLC_Projects/headOrientation-moving_arudino-JG-2019-06-27/evaluation-results/iteration-0/headOrientation-moving_arudinoJun27-trainset95shuffle1  already exists!
Running  DeepCut_resnet50_headOrientation-moving_arudinoJun27shuffle1_230000  with # of trainingiterations: 230000
This net has already been evaluated!
The network is evaluated and the results are stored in the subdirectory 'evaluation_results'.
If it generalizes well, choose the best model for prediction and update the config file with the appropriate index for the 'snapshotindex'.
Use the function 'analyze_video' to make predictions on new videos.
Otherwise consider retraining the network (see DeepLabCut workflow Fig 2)
```

Did the DEMO run smoothly on your end?

**Comment by ghost** [comment]
Also the first time I re-ran it, with new collab template, it Analyzed the data for around 3 min, but still threw the same error.

```
WARNING: Logging before flag parsing goes to stderr.
W0708 15:04:16.710197 140267062273920 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/evaluate.py:83: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

W0708 15:04:24.101174 140267062273920 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/nnet/predict.py:22: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

Running  DeepCut_resnet50_-headOrientation-moving_arudinoJun27shuffle1_230000  with # of trainingiterations: 230000
W0708 15:04:26.777046 140267062273920 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/nnet/pose_net.py:74: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

W0708 15:04:27.333162 140267062273920 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/nnet/predict.py:28: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

W0708 15:04:27.550025 140267062273920 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/nnet/predict.py:29: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

W0708 15:04:27.755847 140267062273920 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/nnet/predict.py:30: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.

W0708 15:04:29.703710 140267062273920 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
0it [00:00, ?it/s]Analyzing data...
220it [03:23,  1.21it/s]
Done and results stored for snapshot:  snapshot-230000
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
/usr/lib/python3.6/contextlib.py in __exit__(self, type, value, traceback)
     98             try:
---> 99                 self.gen.throw(type, value, traceback)
    100             except StopIteration as exc:

5 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in get_controller(self, default)
   5651                  self).get_controller(default) as g, context.graph_mode():
-> 5652         yield g
   5653     finally:

/usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/evaluate.py in evaluate_network(config, Shuffles, plotting, show_errors, comparisonbodyparts, gputouse)
    154                 try:
--> 155                     DataMachine = pd.read_hdf(resultsfilename,'df_with_missing')
    156                     print("This net has already been evaluated!")

/usr/local/lib/python3.6/dist-packages/pandas/io/pytables.py in read_hdf(path_or_buf, key, mode, **kwargs)
    346             raise compat.FileNotFoundError(
--> 347                 'File %s does not exist' % path_or_buf)
    348 

FileNotFoundError: File /content/drive/Shared drives/DeepLabCut2.0/DLC_Projects/headOrientation-moving_arudino-JG-2019-06-27/evaluation-results/iteration-0/headOrientation-moving_arudinoJun27-trainset95shuffle1/DeepCut_resnet50_headOrientation-moving_arudinoJun27shuffle1_230000-snapshot-230000.h5 does not exist

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-6-d8366108eec8> in <module>()
      1 get_ipython().magic('matplotlib notebook')
----> 2 deeplabcut.evaluate_network(path_config_file,plotting=True)
      3 
      4 # Here you want to see a low pixel error! Of course, it can only be as good as the labeler, so be sure your labels are good!

/usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/evaluate.py in evaluate_network(config, Shuffles, plotting, show_errors, comparisonbodyparts, gputouse)
    187                     print("Done and results stored for snapshot: ", Snapshots[snapindex])
    188                     DataCombined = pd.concat([Data.T, DataMachine.T], axis=0).T
--> 189                     RMSE,RMSEpcutoff = pairwisedistances(DataCombined, cfg["scorer"], DLCscorer,cfg["pcutoff"],comparisonbodyparts)
    190                     testerror = np.nanmean(RMSE.iloc[testIndices].values.flatten())
    191                     trainerror = np.nanmean(RMSE.iloc[trainIndices].values.flatten())

/usr/local/lib/python3.6/dist-packages/ruamel/yaml/comments.py in __getitem__(self, key)
    689         # type: (Any) -> Any
    690         try:
--> 691             return ordereddict.__getitem__(self, key)
    692         except KeyError:
    693             for merged in getattr(self, merge_attrib, []):

KeyError: 'pcutoff'
```

With the same thing happening again when I run it a second time. (see previous post)

**Comment by MMathisLab** [comment]
Can you post your config file? Also, you can run our Colab demo data and see it’s nothing with our code... so it must be something in your config or project data :/

**Comment by ghost** [comment]
Okay, I'll check with the demo data, but I also trust that it's all good on your end then.

Here's the config file (do you want the pose cfg in the training folder too?)

```
# Project definitions (do not edit)
Task: headOrientation-moving_arudino
scorer: JG
date: Jun27

# Project path (change when moving around)
project_path: /content/drive/Shared drives/DeepLabCut2.0/DLC_Projects/headOrientation-moving_arudino-JG-2019-06-27

# Annotation data set configuration (and individual video cropping parameters)
video_sets:
  /Volumes/JULIA/DeepLabCut_Projects/videos/ML/190531_FP_RR_grooming_Arduino/A2Acre-1028-T1/A2Acre-1028-T1.mkv:
    crop: 0, 640, 0, 480
  /Volumes/JULIA/DeepLabCut_Projects/videos/ML/190531_FP_RR_grooming_Arduino/A2Acre-1028-T2/A2Acre-1028-T2.avi:
    crop: 0, 640, 0, 480
  /Volumes/JULIA/DeepLabCut_Projects/videos/ML/190531_FP_RR_grooming_Arduino/ChATcre-1131-T1/ChATcre-1131-T1-B.avi:
    crop: 0, 640, 0, 480
  /Volumes/JULIA/DeepLabCut_Projects/videos/ML/190531_FP_RR_grooming_Arduino/ChATcre-1131-T3/ChATcre-1131-T3.avi:
    crop: 0, 640, 0, 480
  /Volumes/JULIA/DeepLabCut_Projects/videos/ML/190531_FP_RR_grooming_Arduino/ChATcre-1199-T1/ChATcre-1199-T1.mkv:
    crop: 0, 640, 0, 480
  /Volumes/JULIA/DeepLabCut_Projects/videos/ML/190531_FP_RR_grooming_Arduino/ChATcre-5127-T2/ChATcre-5127-T2.avi:
    crop: 0, 640, 0, 480
  /Volumes/JULIA/DeepLabCut_Projects/videos/ML/190531_FP_RR_grooming_Arduino/D1cre-1002-T2/D1cre-1002-T2.avi:
    crop: 0, 640, 0, 48
  /Volumes/JULIA/DeepLabCut_Projects/videos/ML/190531_FP_RR_grooming_Arduino/D1cre-FasGCAMP-841-T1/D1cre-FasGCAMP-841-T1.avi:
    crop: 0, 640, 0, 480
  /Volumes/JULIA/DeepLabCut_Projects/videos/ML/190531_FP_RR_grooming_Arduino/D1cre-FasGCAMP-841-T2/D1cre-FasGCAMP-841-T2.avi:
    crop: 0, 640, 0, 480
  /Volumes/JULIA/DeepLabCut_Projects/videos/ML/190531_FP_RR_grooming_Arduino/D1cre-1002-T4/D1cre-1002-T4.mkv:
    crop: 0, 640, 0, 480
  /Volumes/JULIA/DeepLabCut_Projects/videos/ML/D2OE-D1cre-June2019-videos/FP-D2OED1cre-1419-T3.mkv:
    crop: 0, 640, 0, 480
bodyparts:
- FiberTipLower
- FiberTipUpper
- fiberBase_R
- fiberBase_L
- fiberBase_C
- earU_R
- earL_R
- earU_L
- earL_L
- eyeU_L
- eyeL_L
- eyeU_R
- eyeL_R
- snout_R
- snout_L
- snout_C
- frontPaw_right
- frontPaw_left
- backPaw_right
- backPaw_left
- light_On
- Top_R
- Top_L
- Bottom_R
- Bottom_L
- Tail_U
- Tail_M
- Tail_L
start: 0
stop: 1
numframes2pick: 20

# Plotting configuration
skeleton: [['FiberTipLower','FiberTipUpper'],['FiberTipLower','fiberBase_R'],['FiberTipLower','fiberBase_L'],['FiberTipLower','fiberBase_C'],['fiberBase_R','fiberBase_C'],['fiberBase_L','fiberBase_C'],['earU_R','earL_R'],['earU_L','earL_L'],['eyeU_L','eyeL_L'],['eyeU_R','eyeL_R'],['eyeL_R','snout_R'],['eyeL_L','snout_L'],['snout_L','snout_C'],['snout_C','snout_R'],['Top_R','Top_L'],['Top_L','Bottom_L'],['Bottom_L','Bottom_R'],['Bottom_R','Top_R'],['earL_R','eyeU_R'],['earL_L','eyeU_L']]
skeleton-color: black
dotsize: 5
alphavalue: 0.8
colormap: jet

# Training,Evaluation and Analysis configuration
TrainingFraction:
- 0.95
iteration: 0
resnet: 50
snapshotindex: -1
batch_size: 40

# Cropping Parameters (for analysis and outlier frame detection)
cropping: true
#if cropping is true for analysis, then set the values here:
x1: 120
x2: 520
y1: 0
y2: 480

# Refinement configuration (parameters from annotation dataset configuration also relevant in this stage)
corner2move2:
- 50
- 50
move2corner: true

```
