### ISSUE TITLE
Attention: /projectnb/ivcgroup/jalal/moth-filtered-Mona-2019-12-06/labeled-data/moth does not appear to have labeled data!

### ISSUE THREAD

**Issue by monajalal** [DeepLabCut/DeepLabCut#522]
I created the following new project:
```
>>> import deeplabcut
>>> deeplabcut.create_new_project('moth-filtered','Mona', ['/projectnb/ivcgroup/jalal/moth.avi'], working_directory='/projectnb/ivcgroup/jalal',copy_videos=True)
Created "/projectnb/ivcgroup/jalal/moth-filtered-Mona-2019-12-06/videos"
Created "/projectnb/ivcgroup/jalal/moth-filtered-Mona-2019-12-06/labeled-data"
Created "/projectnb/ivcgroup/jalal/moth-filtered-Mona-2019-12-06/training-datasets"
Created "/projectnb/ivcgroup/jalal/moth-filtered-Mona-2019-12-06/dlc-models"
Copying the videos
/projectnb/ivcgroup/jalal/moth-filtered-Mona-2019-12-06/videos/moth.avi
Generated "/projectnb/ivcgroup/jalal/moth-filtered-Mona-2019-12-06/config.yaml"

A new project with name moth-filtered-Mona-2019-12-06 is created at /projectnb/ivcgroup/jalal and a configurable file (config.yaml) is stored there. Change the parameters in this file to adapt to your project's needs.
 Once you have changed the configuration file, use the function 'extract_frames' to select frames for labeling.
. [OPTIONAL] Use the function 'add_new_videos' to add new videos to your project (at any stage).
'/projectnb/ivcgroup/jalal/moth-filtered-Mona-2019-12-06/config.yaml'
```
It has the following files/folders:

```
(deeplabcut)[jalal@scc-x05 moth-filtered-Mona-2019-12-06]$ ls
total 67
drwxrwsrwx 26 jalal ivcgroup 32768 Dec  6 19:10 ..
drwxr-sr-x  2 jalal ivcgroup   512 Dec  6 19:10 training-datasets
drwxr-sr-x  2 jalal ivcgroup   512 Dec  6 19:10 dlc-models
drwxr-sr-x  3 jalal ivcgroup   512 Dec  6 19:10 labeled-data
drwxr-sr-x  2 jalal ivcgroup   512 Dec  6 19:10 videos
drwxr-sr-x  6 jalal ivcgroup   512 Dec  6 19:10 .
-rw-r--r--  1 jalal ivcgroup  1151 Dec  6 19:10 config.yaml
(deeplabcut)[jalal@scc-x05 moth-filtered-Mona-2019-12-06]$ ls labeled-data/
total 2
drwxr-sr-x 3 jalal ivcgroup 512 Dec  6 19:10 .
drwxr-sr-x 2 jalal ivcgroup 512 Dec  6 19:10 moth
drwxr-sr-x 6 jalal ivcgroup 512 Dec  6 19:10 ..
```

When I try to convert the csv to h5 I get the following error:
```
>>> deeplabcut.convertcsv2h5("/projectnb/ivcgroup/jalal/moth-filtered-Mona-2019-12-06/config.yaml")
Do you want to convert the csv file in folder: /projectnb/ivcgroup/jalal/moth-filtered-Mona-2019-12-06/labeled-data/moth ?
yes/noyes
Attention: /projectnb/ivcgroup/jalal/moth-filtered-Mona-2019-12-06/labeled-data/moth does not appear to have labeled data!
>>> quit()
```
This is what I have in `labeled-data/moth` folder:
```
(deeplabcut)[jalal@scc-x05 moth]$ pwd 
/projectnb/ivcgroup/jalal/moth-filtered-Mona-2019-12-06/labeled-data/moth
(deeplabcut)[jalal@scc-x05 moth]$ ls -l *.png | head
-rw-r--r-- 1 jalal ivcgroup 174702 Dec  6 19:11 frame001.png
-rw-r--r-- 1 jalal ivcgroup 174702 Dec  6 19:11 frame002.png
-rw-r--r-- 1 jalal ivcgroup 174702 Dec  6 19:11 frame003.png
-rw-r--r-- 1 jalal ivcgroup 174702 Dec  6 19:11 frame004.png
-rw-r--r-- 1 jalal ivcgroup 174702 Dec  6 19:11 frame005.png
-rw-r--r-- 1 jalal ivcgroup 174702 Dec  6 19:11 frame006.png
-rw-r--r-- 1 jalal ivcgroup 174702 Dec  6 19:11 frame007.png
-rw-r--r-- 1 jalal ivcgroup 174702 Dec  6 19:11 frame008.png
-rw-r--r-- 1 jalal ivcgroup 174702 Dec  6 19:11 frame009.png
-rw-r--r-- 1 jalal ivcgroup 174702 Dec  6 19:11 frame010.png
(deeplabcut)[jalal@scc-x05 moth]$ ls *.csv
-rw-r--r-- 1 jalal ivcgroup 69483 Dec  6 19:12 moth2Dpose.csv
(deeplabcut)[jalal@scc-x05 moth]$ head moth2Dpose.csv 
scorer,Mona,Mona,Mona,Mona,Mona,Mona,Mona,Mona
bodyparts,head,head,rightWingTip,rightWingTip,leftWingTip,leftWingTip,abdomenTip,abdomenTip
coords,x,y,x,y,x,y,x,y
labeled-data/moth/frame001.png,494.2244837,240.7295774,712.0363866,269.7266196,311.2984476,337,477.7910148,292.7525652
labeled-data/moth/frame002.png,494.9006156,240.4824949,695.4159712,234.3256987,286.159703,297.5113911,475.6516914,292.7525652
labeled-data/moth/frame003.png,495.1558141,241.1202971,664.0746166,184.8685298,280.2320841,238.2186337,474.6163777,294.0813382
labeled-data/moth/frame004.png,495.4410572,242.0584384,620.5228669,140.8098868,298.6642961,175.1677438,474.4262156,295.5406691
labeled-data/moth/frame005.png,495.7263003,242.9965797,602.1612651,119.9858157,323.3444567,134.9478643,471.5737844,299.710186
labeled-data/moth/frame006.png,496.12,243.31,617.3570735,115.1268658,340.0202409,124.7100768,469.6721635,302.6288478
labeled-data/moth/frame007.png,496.19,243.74,640.7839446,126.2330371,333.3499272,133.4853233,467.7705427,306.5898889


```

So could you please help fix this error so that I can convert this CSV to h5?

Here is the config.yaml file:
```
# Project definitions (do not edit)
Task: moth-filtered
scorer: Mona
date: Dec6

# Project path (change when moving around)
project_path: /projectnb/ivcgroup/jalal/moth-filtered-Mona-2019-12-06

# Annotation data set configuration (and individual video cropping parameters)
video_sets:
  /projectnb/ivcgroup/jalal/moth-filtered-Mona-2019-12-06/videos/moth.avi:
    crop: 0, 800, 0, 600
bodyparts:
- head
- rightWingTip
- leftWingTip
- abdomenTip
start: 0
stop: 1
numframes2pick: 100

# Plotting configuration
skeleton:
- - bodypart1
  - bodypart2
- - objectA
  - bodypart3
skeleton_color: black
pcutoff: 0.1
dotsize: 12
alphavalue: 0.7
colormap: jet

# Training,Evaluation and Analysis configuration
TrainingFraction:
- 0.95
iteration: 0
resnet:
snapshotindex: -1
batch_size: 8

# Cropping Parameters (for analysis and outlier frame detection)
cropping: false
#if cropping is true for analysis, then set the values here:
x1: 0
x2: 640
y1: 277
y2: 624

# Refinement configuration (parameters from annotation dataset configuration also relevant in this stage)
corner2move2:
- 50
- 50
move2corner: true
default_net_type: resnet_50
default_augmenter: default

```
