### ISSUE TITLE
Issue with Pose estimation video compared to generated Tracklets

### ISSUE THREAD

**Issue by CalvinLloyd117** [DeepLabCut/DeepLabCut#937]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). Please fill out the template completely, including the full "traceback" and input code that you ran to hit this error.

**Your Operating system and DeepLabCut version**

OS: Windows 10
DeepLabCut Version: 2.2b8
Anaconda env used: The one DLC provides (DLC-GPU)

**Describe the problem**

Hello. I have been using DLC for a while now, though I still consider myself a novice. I have been using MA DLC to track groups of vervet monkeys, and have been having a pretty good time with the program so far, apart from a few issues which have been resolved. I have extracted and manually labeled around 200 frames (20 frames or so from each of 10 videos, depending on the video length). A couple of the longer videos I have labeled around 50 frames). I created the training dataset, and then trained the network for 100,000 iterations on my GTX 1070TI. I proceeded to evaluate the network and cross-validate as normal. 

I ran the analyse videos function on one of the shorter videos using both box and skeletal tracking. Both provided similar results. I was also sure to select "create video for checking detections". After analyzing, I watched the generated video to verify that the pose estimation was good. I was incredibly happy with the quality of the markers on the vervets, though there was some jitter, which I expected. Nonetheless, all of the colored markers appeared to be in the correct spots at least 90% of the time. 

Then I proceed to convert to tracklets and attempt to refine. This is where my problem began. There were either very few tracklets, none at all, or they were entirely in the wrong locations when compared to the 'create video for checking detections'. I did some tinkering with the inference_config.yaml, and attempted to follow some advice found in the forums and in the github issues. Nothing I tried seemed to resemble the great tracking I received from 'create video for checking detections'. I am wondering what is going wrong here? Refining tracklets at this point (even with my best variant of the inference_config) will involve moving each and every tracklet, reassigning entities, etc for nearly every frame, not to mention you cannot replace missing tracklets in the Refine Tracklets GUI for ones that are not generated by the system. Is this the intended workflow? Have I made a mistake is training? I am really not certain. I figured 200 labelled frames would be enough (which it seems to be for creating video for checking detections). 

Anyhow, I would really appreciate any input, advice, or help that you are willing to provide. 

Hope to hear back from you.

**Inference_config**
Here is the content of the inference_config.yaml that I am using. Most of it was generated by the system, but I have been tinkering with the values that are not cross validated (like pafthreshold).

```
variant: 0
minimalnumberofconnections: 4
averagescore: 0.1
distnormalization: 1500
distnormalizationLOWER: 0
detectionthresholdsquare: 0
addlikelihoods: 0.15
pafthreshold: 0.03

method: m1
withid: false
topktoretain: 3
upperbound_factor: 1.25
lowerbound_factor: .75
boundingboxslack: 0
max_age: 200
min_hits: 3
iou_threshold: 0.2
```

**config.yaml**
```
# Project definitions (do not edit)
Task: Vigilence
scorer: Calvin
date: Jul2
multianimalproject: true

    # Project path (change when moving around)

project_path: S:\Documents\Barret-HenziRA\Vigilence-Calvin-2020-07-02

    # Annotation data set configuration (and individual video cropping parameters)
video_sets:
  ? S:\Documents\Barret-HenziRA\Vigilence-Calvin-2020-07-02\videos\ITE do not mind
    my comments!_cropped\ITE do not mind my comments!_cropped.mp4
  : crop: 0, 400, 0, 400
  S:\Documents\Barret-HenziRA\Vigilence-Calvin-2020-07-02\videos\20170626 095735_cropped\20170626 095735_cropped.mp4:
    crop: 0, 400, 0, 400
  S:\Documents\Barret-HenziRA\Vigilence-Calvin-2020-07-02\videos\20170922_133351_cropped\20170922_133351_cropped.mp4:
    crop: 0, 400, 0, 400
  S:\Documents\Barret-HenziRA\Vigilence-Calvin-2020-07-02\videos\IMG_2379_cropped\IMG_2379_cropped.MOV:
    crop: 0, 400, 0, 400
  S:\Documents\Barret-HenziRA\Vigilence-Calvin-2020-07-02\videos\P6160026_cropped\P6160026_cropped.MOV:
    crop: 0, 400, 0, 400
  S:\Documents\Barret-HenziRA\Vigilence-Calvin-2020-07-02\videos\P6270395_cropped\P6270395_cropped.MOV:
    crop: 0, 400, 0, 400
  S:\Documents\Barret-HenziRA\Vigilence-Calvin-2020-07-02\videos\P7260647_cropped\P7260647_cropped.MOV:
    crop: 0, 400, 0, 400
  S:\Documents\Barret-HenziRA\Vigilence-Calvin-2020-07-02\videos\P9180068_cropped\P9180068_cropped.MOV:
    crop: 0, 400, 0, 400
  S:\Documents\Barret-HenziRA\Vigilence-Calvin-2020-07-02\videos\PA030770_cropped\PA030770_cropped.MOV:
    crop: 0, 400, 0, 400
  S:\Documents\Barret-HenziRA\Vigilence-Calvin-2020-07-02\videos\PA191044_cropped\PA191044_cropped.MOV:
    crop: 0, 400, 0, 400
  S:\Documents\Barret-HenziRA\Vigilence-Calvin-2020-07-02\videos\PA231187_cropped\PA231187_cropped.MOV:
    crop: 0, 400, 0, 400
individuals:
- vervet1
- vervet2
- vervet3
- vervet4
- vervet5
- vervet6
- vervet7
- vervet8
- vervet9
- vervet10
- vervet11
- vervet12
- vervet13
- vervet14
- vervet15

uniquebodyparts: []
multianimalbodyparts:
- lefteye
- righteye
- leftear
- rightear
- nose
- chin
- lefthand
- leftelbow
- leftshoulder
- righthand
- rightelbow
- rightshoulder
- topback
- midback
- lowerback
- leftfoot
- leftknee
- lefthip
- rightfoot
- rightknee
- righthip
- tailbase
- tailmid
- tailtip
skeleton:
- - lefteye
  - righteye
- - lefteye
  - nose
- - righteye
  - nose
- - lefteye
  - leftear
- - righteye
  - rightear
- - leftear
  - topback
- - rightear
  - topback
- - nose
  - chin
- - nose
  - leftear
- - nose
  - rightear
- - chin
  - leftshoulder
- - chin
  - rightshoulder
- - chin
  - topback
- - leftear
  - leftshoulder
- - rightear
  - rightshoulder
- - chin
  - leftear
- - chin
  - rightear
- - rightshoulder
  - leftshoulder
- - rightshoulder
  - rightelbow
- - rightelbow
  - righthand
- - rightelbow
  - leftelbow
- - righthand
  - lefthand
- - leftshoulder
  - leftelbow
- - leftshoulder
  - lefthand
- - leftshoulder
  - topback
- - rightshoulder
  - righthand
- - rightshoulder
  - topback
- - topback
  - midback
- - topback
  - righthip
- - topback
  - lefthip
- - lowerback
  - midback
- - lowerback
  - lefthip
- - lowerback
  - righthip
- - lowerback
  - tailmid
- - lowerback
  - tailbase
- - leftelbow
  - lefthand
- - rightear
  - midback
- - leftear
  - midback
- - leftshoulder
  - midback
- - leftshoulder
  - lefthip
- - rightshoulder
  - righthip
- - rightshoulder
  - midback
- - midback
  - tailbase
- - midback
  - lefthip
- - midback
  - righthip
- - lefthip
  - righthip
- - lefthip
  - leftknee
- - lefthip
  - tailbase
- - righthip
  - tailbase
- - righthip
  - rightfoot
- - lefthip
  - leftfoot
- - leftknee
  - leftfoot
- - righthip
  - rightknee
- - rightknee
  - rightfoot
- - rightknee
  - leftknee
- - rightfoot
  - leftfoot
- - rightfoot
  - righthand
- - leftfoot
  - lefthand
- - tailbase
  - tailmid
- - tailmid
  - tailtip
- - tailbase
  - tailtip
- - righthip
  - tailmid
- - righthip
  - tailtip
- - lefthip
  - tailmid
- - lefthip
  - tailtip

bodyparts: MULTI!
start: 0
stop: 1
numframes2pick: 30

    # Plotting configuration
skeleton_color: black
pcutoff: 0.6
dotsize: 3
alphavalue: 0.7
colormap: plasma

    # Training,Evaluation and Analysis configuration
TrainingFraction:
- 0.95
iteration: 0
default_net_type: resnet_50
default_augmenter: multi-animal-imgaug
snapshotindex: -1
batch_size: 8

    # Cropping Parameters (for analysis and outlier frame detection)
cropping: false
croppedtraining: true
    #if cropping is true for analysis, then set the values here:
x1: 0
x2: 640
y1: 277
y2: 624

    # Refinement configuration (parameters from annotation dataset configuration also relevant in this stage)
corner2move2:
- 50
- 50
move2corner: true
video_sets_original:
  ? S:\Documents\Barret-HenziRA\Vigilence-Calvin-2020-07-02\videos\ITE do not mind
    my comments!\ITE do not mind my comments!.mp4
  : crop: 0, 1920, 0, 1080
  S:\Documents\Barret-HenziRA\Vigilence-Calvin-2020-07-02\videos\20170626 095735\20170626 095735.mp4:
    crop: 0, 1920, 0, 1080
  S:\Documents\Barret-HenziRA\Vigilence-Calvin-2020-07-02\videos\20170922_133351\20170922_133351.mp4:
    crop: 0, 1920, 0, 1080
  S:\Documents\Barret-HenziRA\Vigilence-Calvin-2020-07-02\videos\IMG_2379\IMG_2379.MOV:
    crop: 0, 1280, 0, 720
  S:\Documents\Barret-HenziRA\Vigilence-Calvin-2020-07-02\videos\P6160026\P6160026.MOV:
    crop: 0, 1920, 0, 1080
  S:\Documents\Barret-HenziRA\Vigilence-Calvin-2020-07-02\videos\P6270395\P6270395.MOV:
    crop: 0, 1920, 0, 1080
  S:\Documents\Barret-HenziRA\Vigilence-Calvin-2020-07-02\videos\P7260647\P7260647.MOV:
    crop: 0, 1920, 0, 1080
  S:\Documents\Barret-HenziRA\Vigilence-Calvin-2020-07-02\videos\P9180068\P9180068.MOV:
    crop: 0, 1920, 0, 1080
  S:\Documents\Barret-HenziRA\Vigilence-Calvin-2020-07-02\videos\PA030770\PA030770.MOV:
    crop: 0, 1920, 0, 1080
  S:\Documents\Barret-HenziRA\Vigilence-Calvin-2020-07-02\videos\PA191044\PA191044.MOV:
    crop: 0, 1920, 0, 1080
  S:\Documents\Barret-HenziRA\Vigilence-Calvin-2020-07-02\videos\PA231187\PA231187.MOV:
    crop: 0, 1920, 0, 1080
```

Not sure if these will help to evaluate the issue or not.
