### ISSUE TITLE
Issue cropping videos in analyze_videos (cannot unpack non-iterable bool object)

### ISSUE THREAD

**Issue by BaduraLab** [DeepLabCut/DeepLabCut#978]
Hello! 
Hope someone can help with this, thanks in advanced :) 

**Your Operating system and DeepLabCut version**
Ubuntu 18.04.4 LTS, anaconda env, deeplabcut 2.2b6

**Describe the problem**
I'm trying to crop videos while using deeplabcut.analyze_videos function.
I have set cropping to True and I have changed the cropping parameters in the config file. 
Given the error, it looks like it is not recognising the cfg x1, x2, y1, y2 that I have modfied in the config. 

```
In [13]: deeplabcut.analyze_videos(config_path,['/home/mariaroa@dc.cube.local/DLC_locom
    ...: ouse/locomouse_uncropped/8B#10_Pax5-p.R31Q_D3_6_L-R.mp4'], videotype='mp4', sa
    ...: ve_as_csv=True, cropping=True)
```

Full terminal output with error: 

```
TypeError                                 Traceback (most recent call last)
<ipython-input-13-313e0830977d> in <module>
----> 1 deeplabcut.analyze_videos(config_path,['/home/mariaroa@dc.cube.local/DLC_locomouse/locomouse_uncropped/8B#10_Pax5-p.R31Q_D3_6_L-R.mp4'], videotype='mp4', save_as_csv=True, cropping=True)

~/anaconda3/envs/DLC-GPU/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/predict_videos.py in analyze_videos(config, videos, videotype, shuffle, trainingsetindex, gputouse, save_as_csv, destfolder, batchsize, cropping, get_nframesfrommetadata, TFGPUinference, dynamic, modelprefix, c_engine, robust_nframes)
    161     if cropping is not None:
    162         cfg["cropping"] = True
--> 163         cfg["x1"], cfg["x2"], cfg["y1"], cfg["y2"] = cropping
    164         print("Overwriting cropping parameters:", cropping)
    165         print("These are used for all videos, but won't be save to the cfg file.")

TypeError: cannot unpack non-iterable bool object
```

**Comment by MMathisLab** [comment]
Seems an error in the config.yaml; can you post what you modified?

In general, this function (cropping) is rather old and should be depreciated; we replaced this with dynamic cropping ~ 1 year ago, so you might want to use this instead. 

```python
dynamic: triple containing (state,detectiontreshold,margin)
       If the state is true, then dynamic cropping will be performed. That means that if an object is detected (i.e. any body part > detectiontreshold),
       then object boundaries are computed according to the smallest/largest x position and smallest/largest y position of all body parts. This  window is
       expanded by the margin and from then on only the posture within this crop is analyzed (until the object is lost, i.e. <detectiontreshold). The
       current position is utilized for updating the crop window for the next frame (this is why the margin is important and should be set large
       enough given the movement of the animal).
```

**Comment by BaduraLab** [comment]
Thanks @MMathisLab 
Here is how the config.yaml looks like:

```
# Annotation data set configuration (and individual video cropping parameters)
video_sets:
  /home/moadb/Documents/Amy_DLC/FullVideo_TrainingVideos/Basler acA2000-165umNIR (22450978)_20200304_124418113.mp4:
    crop: 0, 1400, 0, 230
  /home/moadb/Documents/Amy_DLC/FullVideo_TrainingVideos/Basler acA2000-165umNIR (22450978)_20200723_163724966.mp4:
    crop: 0, 1400, 0, 230
  /home/moadb/Documents/Amy_DLC/FullVideo_TrainingVideos/Basler acA2000-165umNIR (22450978)_20200227_110012881.mp4:
    crop: 0, 1400, 0, 230
  /home/moadb/Documents/Amy_DLC/FullVideo_TrainingVideos/Basler acA2000-165umNIR (22450978)_20200227_110105590.mp4:
    crop: 0, 1400, 0, 230
bodyparts:
- nose
- LF
- LB
- RF
- RB
- T1
- T5
- T3
- T2
- T4
- side_nose
- side_earBase
- side_RF
- side_RB
- side_LF
- side_LB
- side_T1
- side_T5
- side_T3
- side_T2
- side_T4
start: 0
stop: 1
numframes2pick: 20

# Plotting configuration
skeleton: [[nose, T1], [LF, RF], [LB, RB], [LF, LB], [RF, RB], [T1, T2, T3, T4, T5],
  [LF, BR], [RF, LR]]
skeleton_color: black
pcutoff: 0.6
dotsize: 6
alphavalue: 0.7
colormap: jet

# Training,Evaluation and Analysis configuration
TrainingFraction:
- 0.95
iteration: 5
resnet:
snapshotindex: -1
batch_size: 8

# Cropping Parameters (for analysis and outlier frame detection)
cropping: True
#if cropping is true for analysis, then set the values here:
x1: 300
x2: 0
y1: 0
y2: 0

# Refinement configuration (parameters from annotation dataset configuration also relevant in this stage)
corner2move2:
- 50
- 50
move2corner: true
default_net_type: resnet_50
default_augmenter: default
```
I'll try dynamic cropping as well
